# 加减运算

In [16]:
import numpy as np
import colorama as co

from display import aprint
from array_ import arange_by_shape

## 1. 基本加法运算

两个形状相同的数组可以进行加法运算, 例如:

$\begin{bmatrix}
    \begin{bmatrix}
        1 & 2 & 3 & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        2 & 3 & 4 & 5
    \end{bmatrix} \\
    \begin{bmatrix}
        3 & 4 & 5 & 6
    \end{bmatrix}
\end{bmatrix} + \begin{bmatrix}
    \begin{bmatrix}
        10 & 20 & 30 & 40
    \end{bmatrix} \\
    \begin{bmatrix}
        20 & 30 & 40 & 50
    \end{bmatrix} \\
    \begin{bmatrix}
        30 & 40 & 50 & 60
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        11 & 22 & 33 & 44
    \end{bmatrix} \\
    \begin{bmatrix}
        22 & 33 & 44 & 55
    \end{bmatrix} \\
    \begin{bmatrix}
        33 & 44 & 55 & 66
    \end{bmatrix}
\end{bmatrix}$

从上面矩阵加法结果可扩展, 两个形状相同的数组相加, 即将两个数组位置相同 (同维度， 同索引) 的元素相加, 并在结果数组相同位置存放结果元素

### 1.1. 一维数组相加

一维数组相加即向量相加, 其结果仍为一个向量, 相当于把两个向量相同位置的值相加

In [17]:
# 将两个长度相同的一维数组相加
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
aprint(
    "一维数组相加:",
    {
        "a": a,
        "b": b,
        "a + b": a + b,
    },
)

一维数组相加:
> a:
[1 2 3 4], shape=(4,)
> b:
[5 6 7 8], shape=(4,)
> a + b:
[ 6  8 10 12], shape=(4,)


### 1.2. 二维数组相加

二维数组相加即矩阵相加, 其结果仍为一个矩阵, 相当于将两个矩阵相同位置的值相加

In [18]:
# 将两个形状相同的二维数组相加
a = np.array(
    [
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
    ]
)
b = np.array(
    [
        [10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60],
    ]
)
aprint(
    "\n二维数组相加:",
    {
        "a": a,
        "b": b,
        "a + b": a + b,
    },
)


二维数组相加:
> a:
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]], shape=(3, 4)
> b:
[[10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]], shape=(3, 4)
> a + b:
[[11 22 33 44]
 [22 33 44 55]
 [33 44 55 66]], shape=(3, 4)


### 1.3. 多维数组相加

多维数组相加, 其结果仍为同形状的多维数组, 相当于将两个多维数组同维度同位置的值相加

In [19]:
# 将两个形状相同的三维数组相加
a = np.arange(1, 25).reshape(2, 3, 4)
b = np.arange(10, 250, step=10).reshape(2, 3, 4)
aprint(
    "\n三维数组相加:",
    {
        "a": a,
        "b": b,
        "a + b": a + b,
    },
)


三维数组相加:
> a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
> b:
[[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]

 [[130 140 150 160]
  [170 180 190 200]
  [210 220 230 240]]], shape=(2, 3, 4)
> a + b:
[[[ 11  22  33  44]
  [ 55  66  77  88]
  [ 99 110 121 132]]

 [[143 154 165 176]
  [187 198 209 220]
  [231 242 253 264]]], shape=(2, 3, 4)


## 2. 数组无法相加的情况

对于两个形状不同的数组, 无法进行加法运算, 除非其中一个数组满足可广播条件

In [20]:
# 测试长度不同的两个一维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([1, 2, 3])
    b = np.array([5, 6, 7, 8])
    a + b  # type: ignore
except ValueError as e:
    print(f"{co.Fore.RED}一维数组相加失败: {e}{co.Fore.RESET}")

# 测试两个列长度不同的二维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6, 7], [8, 9, 10]])
    a + b  # type: ignore
except ValueError as e:
    print(f"{co.Fore.RED}二维数组相加失败: {e}{co.Fore.RESET}")

一维数组相加失败: operands could not be broadcast together with shapes (3,) (4,) 
二维数组相加失败: operands could not be broadcast together with shapes (2,2) (2,3) 


## 3. 加法定律

数组的加法满足如下定律:

- $A + B = B + A$
- $(A + B) + C = A + (B + C)$
- $A + B = C \Leftrightarrow A = C - B$

### 3.1. 加法交换律

`A` 和 `B` 为可相加的数组, 则加法交换律满足 $A + B = B + A$

In [21]:
a = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
    ]
)

b = np.array(
    [
        [0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
    ]
)

aprint(
    "加法交换律:",
    {
        "a": a,
        "b": b,
        "a + b": a + b,
        "b + a": b + a,
    },
)

加法交换律:
> a:
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)
> b:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]], shape=(2, 4)
> a + b:
[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]], shape=(2, 4)
> b + a:
[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]], shape=(2, 4)


### 3.2. 加法结合律:



对于可相加的数组 `A`, `B` 和 `C`, 则加法结合律满足 $(A + B) + C = A + (B + C)$

In [22]:
a = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
    ]
)

b = np.array(
    [
        [10, 20, 30, 40],
        [50, 60, 70, 80],
    ]
)

c = np.array(
    [
        [0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
    ]
)

aprint(
    "加法结合律:",
    {
        "a": a,
        "b": b,
        "c": c,
        "(a + b) + c": (a + b) + c,
        "a + (b + c)": a + (b + c),
    },
)

加法结合律:
> a:
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)
> b:
[[10 20 30 40]
 [50 60 70 80]], shape=(2, 4)
> c:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]], shape=(2, 4)
> (a + b) + c:
[[11.1 22.2 33.3 44.4]
 [55.5 66.6 77.7 88.8]], shape=(2, 4)
> a + (b + c):
[[11.1 22.2 33.3 44.4]
 [55.5 66.6 77.7 88.8]], shape=(2, 4)


### 3.3. 等值交换

$A + B = C \Leftrightarrow A = C - B$

In [23]:
a = np.array(
    [
        [1.0, 2.0, 3.0, 4.0],
        [5.0, 6.0, 7.0, 8.0],
    ]
)

b = np.array(
    [
        [0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
    ]
)

c = a + b

aprint(
    "加法交换律:",
    {
        "a": a,
        "b": b,
        "c = a + b": a + b,
        "a = c - b": c - b,
    },
)

加法交换律:
> a:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4)
> b:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]], shape=(2, 4)
> c = a + b:
[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]], shape=(2, 4)
> a = c - b:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4)
