# 减法运算

In [6]:
import numpy as np
import colorama as co

from display import aprint
from array_ import arange_by_shape

## 1. 减法运算

两个形状相同的数组可以进行减法运算, 例如:

$\begin{bmatrix}
    \begin{bmatrix}
        10 & 20 & 30 & 40
    \end{bmatrix} \\
    \begin{bmatrix}
        20 & 30 & 40 & 50
    \end{bmatrix} \\
    \begin{bmatrix}
        30 & 40 & 50 & 60
    \end{bmatrix}
\end{bmatrix} - \begin{bmatrix}
    \begin{bmatrix}
        1 & 2 & 3 & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        2 & 3 & 4 & 5
    \end{bmatrix} \\
    \begin{bmatrix}
        3 & 4 & 5 & 6
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        9 & 18 & 27 & 36
    \end{bmatrix} \\
    \begin{bmatrix}
        18 & 27 & 36 & 45
    \end{bmatrix} \\
    \begin{bmatrix}
        27 & 36 & 45 & 54
    \end{bmatrix}
\end{bmatrix}$

从上面矩阵减法结果可扩展, 两个形状相同的数组相减, 即将两个数组位置相同 (同维度， 同索引) 的元素相减, 并在结果数组相同位置存放结果元素

### 1.1. 一维数组相减

一维数组相减和一维数组相加规则相同

In [7]:
# 将两个长度相同的一维数组相减
a = np.array([8, 7, 6, 5])
b = np.array([1, 2, 3, 4])
aprint(
    "一维数组相减:",
    {
        "a": a,
        "b": b,
        "a - b": a - b,
    },
)

一维数组相减:
> a:
[8 7 6 5], shape=(4,)
> b:
[1 2 3 4], shape=(4,)
> a - b:
[7 5 3 1], shape=(4,)


### 1.2. 二维数组相减

二维数组相减和二维数组相加规则相同

In [8]:
# 将两个形状相同的二维数组相减
a = np.array(
    [
        [10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60],
    ]
)
b = np.array(
    [
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
    ]
)
aprint(
    "\n二维数组相减:",
    {
        "a": a,
        "b": b,
        "a - b": a - b,
    },
)


二维数组相减:
> a:
[[10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]], shape=(3, 4)
> b:
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]], shape=(3, 4)
> a - b:
[[ 9 18 27 36]
 [18 27 36 45]
 [27 36 45 54]], shape=(3, 4)


### 1.3. 多维数组相减

多维数组相减和多维数组相加规则相同

In [9]:
# 将两个形状相同的三维数组相减
a = np.arange(10, 250, step=10).reshape(2, 3, 4)
b = np.arange(1, 25).reshape(2, 3, 4)
aprint(
    "\n三维数组相减:",
    {
        "a": a,
        "b": b,
        "a - b": a - b,
    },
)


三维数组相减:
> a:
[[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]

 [[130 140 150 160]
  [170 180 190 200]
  [210 220 230 240]]], shape=(2, 3, 4)
> b:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
> a - b:
[[[  9  18  27  36]
  [ 45  54  63  72]
  [ 81  90  99 108]]

 [[117 126 135 144]
  [153 162 171 180]
  [189 198 207 216]]], shape=(2, 3, 4)


## 2. 数组无法相减的情况

对于两个形状不同的数组, 无法进行减法运算, 除非其中一个数组满足可广播条件

In [10]:
# 测试长度不同的两个一维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([1, 2, 3])
    b = np.array([5, 6, 7, 8])
    a - b  # type: ignore
except ValueError as e:
    print(f"{co.Fore.RED}一维数组相加失败: {e}{co.Fore.RESET}")

# 测试两个列长度不同的二维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6, 7], [8, 9, 10]])
    a - b  # type: ignore
except ValueError as e:
    print(f"{co.Fore.RED}二维数组相加失败: {e}{co.Fore.RESET}")

一维数组相加失败: operands could not be broadcast together with shapes (3,) (4,) 
二维数组相加失败: operands could not be broadcast together with shapes (2,2) (2,3) 
