# 乘法运算

In [8]:
import numpy as np
import colorama as co

from display import aprint
from array_ import arange_by_shape

## 1. 对位相乘

再 Numpy 中, 将两个数组通过 `*` 运算符 (或调用 `np.multiply` 函数) 相乘称为**对位相乘**, 对位相乘的规则为: 将两个数组相同位置元素的值相乘, 然后将结果保存到一个新的数组中

所以对位相乘的两个数组必须具备相同的 shape, 或者数组满足广播条件

$\begin{bmatrix}
    \begin{bmatrix}
        1 & 2 & 3 & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        2 & 3 & 4 & 5
    \end{bmatrix} \\
    \begin{bmatrix}
        3 & 4 & 5 & 6
    \end{bmatrix}
\end{bmatrix} * \begin{bmatrix}
    \begin{bmatrix}
        10 & 20 & 30 & 40
    \end{bmatrix} \\
    \begin{bmatrix}
        20 & 30 & 40 & 50
    \end{bmatrix} \\
    \begin{bmatrix}
        30 & 40 & 50 & 60
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        10 & 40 & 90 & 160
    \end{bmatrix} \\
    \begin{bmatrix}
        40 & 90 & 160 & 250
    \end{bmatrix} \\
    \begin{bmatrix}
        90 & 160 & 250 & 360
    \end{bmatrix}
\end{bmatrix}$

In [9]:
a = np.array(
    [
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
    ]
)

b = np.array(
    [
        [10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60],
    ]
)

aprint(
    "数组和标量相乘:",
    {
        "a": a,
        "b": b,
        "a * b": a * b,
        "np.multiply(a, b)": np.multiply(a, b),
    },
)

数组和标量相乘:
> a:
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]], shape=(3, 4)
> b:
[[10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]], shape=(3, 4)
> a * b:
[[ 10  40  90 160]
 [ 40  90 160 250]
 [ 90 160 250 360]], shape=(3, 4)
> np.multiply(a, b):
[[ 10  40  90 160]
 [ 40  90 160 250]
 [ 90 160 250 360]], shape=(3, 4)


## 2. 点乘

通过 `np.dot` 函数对两个数组相乘称为数组的点乘, 点乘在不同维度的数组上表现如下:

- 两个一维数组的点乘结果是一个标量, 相当于两个向量的乘积
- 两个二维数组的点乘结果是一个二维数组, 即矩阵乘法
- 高维数组 (三维以上) 数组的点乘结果仍是一个高维数组, 相当于多个矩阵的乘法

### 2.1.一维数组点乘

两个一维数组的点乘 (向量乘法), 结果为一个标量, 其计算规则为: 将两个数组对应位置元素相乘后相加的结果

$\begin{bmatrix}
    1 & 2 & 3 & 4
\end{bmatrix} \cdot \begin{bmatrix}
    5 & 6 & 7 & 8
\end{bmatrix} = 1 \cdot 5 + 2 \cdot 6 + 3 \cdot 7 + 4 \cdot 8 = 70$

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

aprint(
    "数组点乘:",
    {
        "a": a,
        "b": b,
        "a · b": np.dot(a, b),
    },
)

数组点乘:
> a:
[1 2 3 4], shape=(4,)
> b:
[5 6 7 8], shape=(4,)
> a · b:
70


### 2.2. 二维数组点乘

两个二维数组的点乘 (矩阵乘法), 结果为一个二维数组, 其运算规则如下图所示:

![X](../../.assets/array_dot.png)

1. 数组 `A` 的第一行元素 ($a_{11}$, $a_{12}$) 和数组 `B` 的第一列元素 ($b_{11}$, $b_{21}$) 对应相乘, 结果相加 ($a_{11} \times b_{11} + a{12} \times b{21}$), 作为结果数组 `C` 的 $c_{11}$ 元素
2. 数组 `A` 的第一行元素 ($a_{11}$, $a_{12}$) 和数组 `B` 的第二列元素 ($b_{12}$, $b_{22}$) 对应相乘, 结果相加 ($a_{11} \times b_{12} + a{12} \times b{22}$), 作为结果数组 `C` 的 $c_{12}$ 元素
3. 数组 `A` 的第一行元素 ($a_{11}$, $a_{12}$) 和数组 `B` 的第三列元素 ($b_{13}$, $b_{23}$) 对应相乘, 结果相加 ($a_{11} \times b_{13} + a{12} \times b{23}$), 作为结果数组 `C` 的 $c_{13}$ 元素
4. 数组 `A` 的第二行元素 ($a_{21}$, $a_{22}$) 和数组 `B` 的第一列元素 ($b_{11}$, $b_{12}$) 对应相乘, 结果相加 ($a_{21} \times b_{11} + a{22} \times b{12}$), 作为结果数组 `C` 的 $c_{21}$ 元素
5. ...
6. 数组 `A` 的第四行元素 ($a_{41}$, $a_{42}$) 和数组 `B` 的第三列元素 ($b_{13}$, $b_{23}$) 对应相乘, 结果相加 ($a_{41} \times b_{13} + a{42} \times b{23}$), 作为结果数组 `C` 的 $c_{43}$ 元素

即对于一个 shape 为 $M_1 \times N_1$ 的矩阵 `A` 和一个 shape 为 $M_2 \times N_2$ 的矩阵 `B`, 则 $A \cdot B$ 结果的 shape 为 $(M_1, N_2)$, 例如下面的矩阵 `A` 和 `B`, 形状分别为 `(4, 2)` 以及 `(2, 3)`, 则 $A \cdot B$ 结果的形状为 `(4, 3)`

$\begin{bmatrix}
    \begin{bmatrix}
        1 & 2
    \end{bmatrix} \\
    \begin{bmatrix}
        3 & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        5 & 6
    \end{bmatrix} \\
    \begin{bmatrix}
        7 & 8
    \end{bmatrix}
\end{bmatrix} \cdot \begin{bmatrix}
    \begin{bmatrix}
        10 & 20 & 30
    \end{bmatrix} \\
    \begin{bmatrix}
        40 & 50 & 60
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        1 \times 10 + 2 \times 40 & 1 \times 20 + 2 \times 50 & 1 \times 30 + 2 \times 60
    \end{bmatrix} \\
    \begin{bmatrix}
        3 \times 10 + 4 \times 40 & 3 \times 20 + 4 \times 50 & 3 \times 30 + 4 \times 60
    \end{bmatrix} \\
    \begin{bmatrix}
        5 \times 10 + 6 \times 40 & 5 \times 20 + 6 \times 50 & 5 \times 30 + 6 \times 60
    \end{bmatrix} \\
    \begin{bmatrix}
        7 \times 10 + 8 \times 40 & 7 \times 20 + 8 \times 50 & 7 \times 30 + 8 \times 60
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        90 & 120 & 150
    \end{bmatrix} \\
    \begin{bmatrix}
        190 & 260 & 330
    \end{bmatrix} \\
    \begin{bmatrix}
        290 & 400 & 510
    \end{bmatrix} \\
    \begin{bmatrix}
        390 & 540 & 690
    \end{bmatrix}
\end{bmatrix}$

故二维数组的点乘 (即矩阵相乘) 要求两个二维数组 `A` 与 `B`, `A` 的行数必须和 `B` 的列数相等, 点乘的结果是一个二维数组 `C`, `C` 的行数等于 `A` 的行数, `C` 的列数等于 `B` 的列数

对于数组 A ($m \times n$) 以及数组 B ($n \times p$), 则 $A \cdot B$ 结果数组的每一项为: $C_{i,j} = \sum_{k=1}^{n} A_{i,k} \times B_{k,j}$

In [11]:
a = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
    ]
)
b = np.array(
    [
        [10, 20, 30],
        [40, 50, 60],
    ]
)

aprint(
    "数组点乘:",
    {
        "a": a,
        "b": b,
        "a · b": np.dot(a, b),
    },
)

数组点乘:
> a:
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2)
> b:
[[10 20 30]
 [40 50 60]], shape=(2, 3)
> a · b:
[[ 90 120 150]
 [190 260 330]
 [290 400 510]
 [390 540 690]], shape=(4, 3)


如果两个二维数组 `A` 和 `B`, `A` 的行数不等于 `B` 的列数，则无法进行矩阵乘法

In [12]:
a = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
    ]
)
b = np.array(
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90],
    ]
)

try:
    np.dot(a, b)  # type: ignore
except ValueError as e:
    print(f"{co.Fore.RED}数组点乘失败: {e}{co.Fore.RESET}")

数组点乘失败: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


对于二维以上数组的点乘会稍复杂一些, 但最终都会拆分为二维数组的矩阵乘法, 例如对于两个三维数组 `A` 和 `B`, 其 shape 分别为 `(2, 2, 3)` 和 `(2, 3, 2)`, 则 $A \cdot B$ 的计算过程如下:

1. 确定是否可以进行点乘运算: 观察 `A` 数组的最后一维 (`3`) 和 `B` 数组的倒数第二维 (`2`) 是否相等, 如果不相等则无法进行点乘运算;
2. 计算结果的 shape: 将 `A` 数组的最后一维和 `B` 数组的倒数第二维去掉, 其余的维度组合, 得到结果数组的 shape 为 `(2, 2, 2, 2)`;
3. 在计算过程中, 忽略 `A` 数组的最后一维以及 `B` 数组的倒数第二维, 对 `A` 和 `B` 剩余维度进行组合计算, 即对于本例两个三维数组:
   - $\small{C[0, 0, 0, 0] = A[0, 0, :] \cdot B[0, :, 0]}$
   - $\small{C[0, 0, 0, 1] = A[0, 0, :] \cdot B[0, :, 1]}$
   - $\small{C[0, 0, 1, 0] = A[0, 0, :] \cdot B[1, :, 0]}$
   - $\small{C[0, 0, 1, 1] = A[0, 0, :] \cdot B[1, :, 1]}$
   - $\small{C[0, 1, 0, 0] = A[0, 1, :] \cdot B[0, :, 0]}$
   - $\small{C[0, 1, 0, 1] = A[0, 1, :] \cdot B[0, :, 1]}$
   - $\small{C[0, 1, 1, 0] = A[0, 1, :] \cdot B[1, :, 0]}$
   - $\small{C[0, 1, 1, 1] = A[0, 1, :] \cdot B[1, :, 1]}$
   - $\small{C[1, 0, 0, 0] = A[1, 0, :] \cdot B[0, :, 0]}$
   - $\small{C[1, 0, 0, 1] = A[1, 0, :] \cdot B[0, :, 1]}$
   - $\small{C[1, 0, 1, 0] = A[1, 0, :] \cdot B[1, :, 0]}$
   - $\small{C[1, 0, 1, 1] = A[1, 0, :] \cdot B[1, :, 1]}$
   - $\small{C[1, 1, 0, 0] = A[1, 1, :] \cdot B[0, :, 0]}$
   - $\small{C[1, 1, 0, 1] = A[1, 1, :] \cdot B[0, :, 1]}$
   - $\small{C[1, 1, 1, 0] = A[1, 1, :] \cdot B[1, :, 0]}$
   - $\small{C[1, 1, 1, 1] = A[1, 1, :] \cdot B[1, :, 1]}$

计算过程及结果如下:


In [13]:
a = arange_by_shape((2, 2, 3), start=1, step=1)
b = arange_by_shape((2, 3, 2), start=1, step=1)

shape = (*a.shape[:-1], *b.shape[:-2], b.shape[-1])
c = np.empty(shape, dtype=np.int32)

c[0, 0, 0, 0] = np.dot(a[0, 0, :], b[0, :, 0])
c[0, 0, 0, 1] = np.dot(a[0, 0, :], b[0, :, 1])
c[0, 0, 1, 0] = np.dot(a[0, 0, :], b[1, :, 0])
c[0, 0, 1, 1] = np.dot(a[0, 0, :], b[1, :, 1])

c[0, 1, 0, 0] = np.dot(a[0, 1, :], b[0, :, 0])
c[0, 1, 0, 1] = np.dot(a[0, 1, :], b[0, :, 1])
c[0, 1, 1, 0] = np.dot(a[0, 1, :], b[1, :, 0])
c[0, 1, 1, 1] = np.dot(a[0, 1, :], b[1, :, 1])

c[1, 0, 0, 0] = np.dot(a[1, 0, :], b[0, :, 0])
c[1, 0, 0, 1] = np.dot(a[1, 0, :], b[0, :, 1])
c[1, 0, 1, 0] = np.dot(a[1, 0, :], b[1, :, 0])
c[1, 0, 1, 1] = np.dot(a[1, 0, :], b[1, :, 1])

c[1, 1, 0, 0] = np.dot(a[1, 1, :], b[0, :, 0])
c[1, 1, 0, 1] = np.dot(a[1, 1, :], b[0, :, 1])
c[1, 1, 1, 0] = np.dot(a[1, 1, :], b[1, :, 0])
c[1, 1, 1, 1] = np.dot(a[1, 1, :], b[1, :, 1])

aprint(
    "数组点乘:",
    {
        "a": a,
        "b": b,
        "a · b": c,
    },
)

数组点乘:
> a:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)
> b:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2)
> a · b:
[[[[ 22  28]
   [ 58  64]]

  [[ 49  64]
   [139 154]]]


 [[[ 76 100]
   [220 244]]

  [[103 136]
   [301 334]]]], shape=(2, 2, 2, 2)


In [14]:
a = arange_by_shape((2, 2, 3), start=1, step=1)
b = arange_by_shape((2, 3, 2), start=1, step=1)

aprint(
    "数组点乘:",
    {
        "a": a,
        "b": b,
        "a · b": np.dot(a, b),
    },
)

数组点乘:
> a:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)
> b:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2)
> a · b:
[[[[ 22  28]
   [ 58  64]]

  [[ 49  64]
   [139 154]]]


 [[[ 76 100]
   [220 244]]

  [[103 136]
   [301 334]]]], shape=(2, 2, 2, 2)
