# 其它运算

In [ ]:
import numpy as np
import colorama as co

from display import aprint
from array_ import arange_by_shape

## 1. 绝对值

通过 `np.absolute` 函数可以获取一个数组的绝对值, 即得到一个形状和原数组相同的结果数组, 其元素为原数组对应元素的绝对值

函数 `np.absolute` 的别名函数为 `np.abs`, 两者功能完全一致

In [ ]:
a = np.array([[-1, 2, -3], [4, -5, 6]])
aprint(
    "数组元素绝对值:",
    {
        "a": a,
        "np.absolute(a)": np.absolute(a),
        "np.abs(a)": np.abs(a),
    },
)

数组元素绝对值:
● a:
[[-1  2 -3]
 [ 4 -5  6]], shape=(2, 3)
● np.absolute(a):
[[1 2 3]
 [4 5 6]], shape=(2, 3)
● np.abs(a):
[[1 2 3]
 [4 5 6]], shape=(2, 3)
