# 创建数组

Numpy 通过 `NdArray` 类型支持大规模数组操作, 为各类线性数据计算提供了高性能的实现

Numpy 的数组实现分为了几个层次:

- 存储: 指的是数组元素在内存中具体的存储方式 (内存布局), Numpy 是以连续内存空间来存储数组元素的, 具体内存布局又分为 C 模式 (行主序) 或 Fortran 模式 (列主序), 不同的内存布局模式会影响数组元素的迭代访问和计算性能
- 索引: 指的是数组元素如何通过索引访问, 数组索引保证了无论数组以何种内存布局进行存储, 都可以以数学概念上的顺序对数组元素进行访问和计算
- 视图: 当数组产生后, 会同时产生一个视图对象对该数组进行引用, 即通过视图对数组进行访问, 这样可以减少数组元素的复制开销, 除非明确指定需要对数组进行复制

In [217]:
import numpy as np

## 1. 通过集合创建

### 1.1. 通过一维列表对象创建数组

In [218]:
a = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{a}")

一维数组内容:
[1 2 3 4]


### 1.2. 通过二维列表对象创建数组

In [219]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\n二维数组内容:\n{a}")


二维数组内容:
[[1 2 3 4]
 [5 6 7 8]]


### 1.3. 通过三维列表对象创建数组

In [220]:
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24],
        ],
    ]
)
print(f"\n三维数组内容:\n{a}")


三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## 2. 创建元素值为 `0` 数组

通过 `np.zeros` 函数可以创建一个元素值都为 `0` 的数组, 可以通过 `shape` 参数指定数组的形状

### 2.1. 创建元素值为 `0` 的一维数组

In [221]:
a = np.zeros(shape=(4))
print(f"一维数组内容:\n{a}")

一维数组内容:
[0. 0. 0. 0.]


### 2.2. 建元素值为 `0` 的二维数组

In [222]:
a = np.zeros(shape=(3, 4))
print(f"\n二维数组内容:\n{a}")


二维数组内容:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 2.3. 创建元素值为 `0` 的三维数组

In [223]:
a = np.zeros(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{a}")


三维数组内容:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## 3. 创建元素值为 `1` 的数组

通过 `np.ones` 函数可以创建一个元素值都为 `1` 的数组, 可以通过 `shape` 参数指定数组的形状

### 3.1. 创建元素值为 `1` 的一维数组

In [224]:
a = np.ones(shape=(4))
print(f"一维数组内容:\n{a}")

一维数组内容:
[1. 1. 1. 1.]


### 3.2. 创建元素值为 `1` 的二维数组

In [225]:
a = np.ones(shape=(3, 4))
print(f"\n二维数组内容:\n{a}")


二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 3.3. 创建元素值为 `1` 的三维数组

In [226]:
a = np.ones(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{a}")


三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## 4. 创建元素值为 "空" 的数组

通过 `np.empty` 函数创建一个元素值为 "空" 的数组, 通过 `shape` 参数可以指定数组的形状

注意:

- 所谓元素值为 "空" 的数组，指的是直接分配内存, 且不会对元素所用内存进行初始化操作, 所以所分配内存中的内容是未知的 (或保留上次该区域内存使用的值)
- 创建了元素值为 "空" 的数组后, 必须对数组元素值全部进行初始化
- 对于已确定会对数组元素值进行全部初始化的场景, 通过 `np.empty` 函数创建数组可以提升程序效率

### 4.1. 创建元素值为 "空" 的一维数组

In [227]:
a = np.empty(shape=(4))
print(f"一维数组内容:\n{a}")

一维数组内容:
[1. 1. 1. 1.]


### 4.2. 创建元素值为 "空" 的二维数组

In [228]:
a = np.empty(shape=(3, 4))
print(f"\n二维数组内容:\n{a}")


二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4.3. 创建元素值为 "空" 的三维数组

In [229]:
a = np.empty(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{a}")


三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## 5. 创建等差数组

通过 `np.linspace` 函数可以创建一个元素值为**等差数列**的一维数组, 通过:

- `start` 参数指定等差数列的起始值;
- `end` 参数指定等差数列的结束值;
- `num` 参数指定等差数列的元素个数;
- `dtype` 参数指定数组元素的数据类型;
- `retstep` 参数指定是否返回步长

`np.linspace` 函数返回一个 `num` 个元素的数组, 数组的最小值为 `start` 参数指定的值, 数组最大的值为 `end` 参数指定的值, 每相邻两个元素值的差值相同

### 5.1. 差值为整数

如果设定的等差数列的最小值和最大值 (`start` 和 `stop` 参数) 可以被指定个数的元素 (`num` 参数值) 均分, 则等差数列的值将为整数值

In [230]:
a = np.linspace(1, 10, 10)
print(f"数组内容:\n{a}")
print(f"数组差值:\n{np.diff(a)}")

数组内容:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
数组差值:
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 5.2. 差值为小数

如果设定的等差数列的最小值和最大值 (`start` 和 `stop` 参数) 无法被指定个数的元素 (`num` 参数值) 均分, 则等差数列的值将为小数值, 且有精度损失问题

In [231]:
a = np.linspace(1, 10, 20)
print(f"\n数组内容:\n{a}")
print(f"数组差值:\n{np.round(np.diff(a), 4)}")


数组内容:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
数组差值:
[0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737
 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737 0.4737]


## 6. 创建元素值为 `0`~`1` 随机数的数组

通过 `np.random.rand` 函数可以创建元素为随机数的数组, 且数组元素的随机数范围在 `0`~`1` 之间, 该函数可传递多个参数值, 分别表示数组的维度

### 6.1. 创建随机元素值的一维数组

In [232]:
a = np.random.rand(4)
print(f"创建 1 维数组:\n{a}")

创建 1 维数组:
[0.56938208 0.99580193 0.11296485 0.93283413]


### 6.2. 创建随机元素值的二维数组

In [233]:
a = np.random.rand(3, 4)
print(f"\n创建 2 维数组:\n{a}")


创建 2 维数组:
[[0.90372113 0.14729805 0.15013348 0.52061969]
 [0.46166682 0.46021477 0.39766325 0.24017544]
 [0.76157294 0.57247837 0.69640596 0.09788887]]


### 6.3. 创建随机元素值的三维数组

In [234]:
a = np.random.rand(2, 3, 4)
print(f"\n创建 3 维数组:\n{a}")


创建 3 维数组:
[[[0.50770844 0.5375749  0.18672827 0.57572979]
  [0.28600677 0.78928911 0.35335178 0.88565704]
  [0.61832538 0.1914995  0.39485069 0.35655611]]

 [[0.42619636 0.75636908 0.14584617 0.01889916]
  [0.52526896 0.76573538 0.46567385 0.71682639]
  [0.33082588 0.98596636 0.94407613 0.51661612]]]


### 6.4. 创建指定范围随机值元素的数组

无法直接通过 `np.random.rand` 函数创建元素为指定范围内随机数的数组, 但可以通过如下公式创建元素值在 $min$ 和 $max$ 范围内随机数的数组:

$min + (max - min) \times R_{0, 1}$

In [235]:
min_, max_ = 5, 10
a = min_ + (max_ - min_) * (np.random.rand(2, 3, 4))

print(f"\n数组内容:\n{a}")


数组内容:
[[[7.60650322 7.24418995 6.73166695 7.90612833]
  [9.90440298 6.8206884  8.32867736 5.02151687]
  [9.23931452 9.49907078 7.92441686 7.83670552]]

 [[5.84454341 5.89598085 5.61431877 9.66991166]
  [8.66708874 9.55265391 7.1269025  5.91779178]
  [6.50853643 7.72037535 6.30576247 6.84508545]]]


## 7. 创建元素值随机整数的数组

通过 `np.random.randint` 函数可以创建元素值为随机整数值的数组, 且可以通过 `low` 和 `high` 参数指定随机数的范围, 通过 `size` 参数指定数组的形状

### 7.1. 创建随机元素值的一维数组

In [236]:
# 创建元素值为 `1`~`10` 之间随机数的一维数组
a = np.random.randint(1, 10, size=(4,))
print(f"数组内容:\n{a}")

数组内容:
[5 1 1 3]


### 7.2. 创建随机元素值的二维数组

In [237]:
# 创建元素值为 `1`~`10` 之间随机数的二维数组
a = np.random.randint(1, 10, size=(3, 4))
print(f"\n数组内容:\n{a}")


数组内容:
[[7 7 9 3]
 [1 3 3 7]
 [9 3 3 2]]


### 7.3. 创建随机元素值的三维数组

In [238]:
# 创建元素值为 `1`~`10` 之间随机数的三维数组
a = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n数组内容:\n{a}")


数组内容:
[[[1 1 6 4]
  [8 5 4 6]
  [7 1 7 9]]

 [[3 4 4 6]
  [4 9 2 3]
  [7 3 5 8]]]


## 8. 数组存储方式

Numpy 数组支持两种内存布局模式, 包括 "C" 风格的按行元素存储 (行主序) 和 "Fortran" 风格按列元素存储 (列主序)

通过创建数组时指定 `order` 参数, 可以改变数组的存储顺序, 参数值包括:

- `"A"`: 默认, 创建时根据数组的形状自动选择
- `"C"`: "C" 风格按行存储 (行主序)
- `"F"`: "Fortran" 风格按列存储 (列主序)
- `"K"`: 保持原数组的存储顺序

### 8.1. 创建 C 风格存储的数组 (行主序)

In [239]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    order="C",
)
print(f"数组内容:\n{a}, \n元素存储顺序:\n{[int(n) for n in np.nditer(a)]}")  # type: ignore

数组内容:
[[1 2 3]
 [4 5 6]
 [7 8 9]], 
元素存储顺序:
[1, 2, 3, 4, 5, 6, 7, 8, 9]


### 8.2. 创建 Fortran 风格存储的数组 (列主序)

In [240]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    order="F",
)
print(f"数组内容:\n{a}, \n元素存储顺序:\n{[int(n) for n in np.nditer(a)]}")  # type: ignore

数组内容:
[[1 2 3]
 [4 5 6]
 [7 8 9]], 
元素存储顺序:
[1, 4, 7, 2, 5, 8, 3, 6, 9]
