# 数组属性

In [40]:
import numpy as np

## 1. 基本属性

### 1.1. 数组维度 (`ndim`)

`ndim` 属性表示数组的维度, 值为一个整数

#### 1.1.1. 一维数组的 `ndim` 属性

一维数组的 `ndim` 属性值为 `1`

In [41]:
a = np.array([1, 2, 3, 4])
print(f"一维数组:\n{a}, dim={a.ndim}")

一维数组:
[1 2 3 4], dim=1


#### 1.1.2. 二维数组的 `ndim` 属性

二维数组的 `ndim` 属性值为 `2`

In [42]:
a = np.array([[1, 2], [3, 4]])
print(f"\n二维数组:\n{a}, dim={a.ndim}")


二维数组:
[[1 2]
 [3 4]], dim=2


#### 1.1.3. 三维数组的 `ndim` 属性

三维数组的 `ndim` 属性值为 `3`

In [43]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"\n三维数组:\n{a}, dim={a.ndim}")


三维数组:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], dim=3


### 1.2. 数组形状 (`shape`)

`shape` 属性表示数组的形状, 值为一个元组, 表示数组在每个维度的长度, 例如 `shape` 属性值为 `(2, 3)` 的数组, 表示一个有 `2` 行 `3` 列的二维数组

#### 1.2.1. 一维数组的 `shape` 属性

一维数组的形状是一个长度为 `1` 的元组

In [44]:
a = np.array([1, 2, 3, 4])
print(f"一维数组:\n{a}, shape={a.shape}")

一维数组:
[1 2 3 4], shape=(4,)


#### 1.2.2. 二维数组的 `shape` 属性

二维数组的形状是一个长度为 `2` 的元组

In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组:\n{a}, shape={a.shape}")


二维数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4)


#### 1.2.3. 三维数组的 `shape` 属性

三维数组的形状是一个长度为 `3` 的元组

In [46]:
# 获取三维数组的形状, 结果为一个包含三个值的元组, 描述数组的三个维度
a = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组:\n{a}, shape={a.shape}")


三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


### 1.3. 数组长度 (`size`)

`size` 属性表示数组的元素总个数, 和数组的形状无关

#### 1.3.1. 一维数组的 `size` 属性

In [47]:
a = np.arange(1, 25)
print(f"一维数组:\n{a}, size={a.size}")

一维数组:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], size=24


#### 1.3.2. 二维数组的 `size` 属性

In [48]:
a = np.arange(1, 25).reshape(2, -1)
print(f"\n二维数组:\n{a}, size={a.size}")


二维数组:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], size=24


#### 1.3.3. 三维数组的 `size` 属性

In [49]:
a = np.arange(1, 25).reshape(2, 3, 4)
print(f"\n三维数组:\n{a}, size={a.size}")


三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], size=24


### 1.4. 数组元素类型 (`dtype`)

#### 1.4.1. 内置数组类型

In [ ]:
a = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(f"数组:\n{a}, dtype={a.dtype}")

a = a * np.array([0.01])
print(f"\n数组:\n{a}, dtype={a.dtype}")

a = np.array([n >= 0.1 for n in a.flat]).reshape(a.shape)
print(f"\n数组:\n{a}, dtype={a.dtype}")

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], dtype=int64

数组:
[[[0.01000214 0.02000427 0.03000641 0.04000854]
  [0.05001068 0.06001282 0.07001495 0.08001709]
  [0.09001923 0.10002136 0.1100235  0.12002563]]], dtype=float64

数组:
[[[False False False False]
  [False False False False]
  [False  True  True  True]]], dtype=bool


In [55]:
a = np.array(['A', 'B', 'C', 'D'], dtype=np.bytes_)
print(f"数组:\n{a}, dtype={a.dtype}")

数组:
[b'A' b'B' b'C' b'D'], dtype=|S1


## 5. 数组的内存占用

通过数组的 `.itemsize` 属性可以获取数组中每个元素的字节大小, 通过 `.nbytes` 属性可以获取整个数组的字节大小

In [52]:
a = np.arange(10, dtype=np.int8)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.int16)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.int32)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.int64)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.float32)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.float64)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

a = np.arange(10, dtype=np.float128)
print(f"数组: size={a.size}, dtype={a.dtype}, itemsize={a.itemsize}, nbytes={a.nbytes}")

数组: size=10, dtype=int8, itemsize=1, nbytes=10
数组: size=10, dtype=int16, itemsize=2, nbytes=20
数组: size=10, dtype=int32, itemsize=4, nbytes=40
数组: size=10, dtype=int64, itemsize=8, nbytes=80
数组: size=10, dtype=float32, itemsize=4, nbytes=40
数组: size=10, dtype=float64, itemsize=8, nbytes=80
数组: size=10, dtype=float128, itemsize=16, nbytes=160
