# 数组形状

In [1]:
import numpy as np

from display import aprint
from array_ import arange_by_shape

In [2]:
# 定义一个 24 个元素的一维数组
a = np.arange(1, 25)
print(f"数组内容:\n{a}, shape={a.shape}")

# 改变数组的形状, 将一维数组改为二维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
a = a.reshape(2, -1)
print(f"\n数组内容:\n{a}, shape={a.shape}")

# 改变数组的形状, 将二维数组改为三维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
a = a.reshape(2, 3, -1)
print(f"\n数组内容:\n{a}, shape={a.shape}")

# 改变数组的形状, 将三维数组改为一维数组
a = a.reshape(-1)
print(f"\n数组内容:\n{a}, shape={a.shape}")

# 如果目标形状无法达成 (及元素个数无法满足目标形状要求), 则操作失败
# data = data.reshape(2, 5, -1)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
