# 数组形状

In [1]:
import numpy as np
import colorama as co

数组形状用于表示数组的维度和各维度的长度

数组形状是一个元组, 元素的个数表示数组的维数, 元素的值表示对应维的长度

## 1. `.shape` 属性

可以通过数组对象的 `.shape` 属性获取数组的形状

一维数组形状

In [2]:
# 创建一维数组
a = np.array([1, 2, 3, 4, 5])

# 获取数组形状, 一维数组的形状为只有一项的元组, 元组元素值为数组长度
print(f"数组: {a}, shape={a.shape}, len(a)={len(a)}")

数组: [1 2 3 4 5], shape=(5,), len(a)=5


多维数组形状

In [3]:
# 创建一个三维数组
a = np.arange(1, 25).reshape(2, 3, 4)

# 输出数组的形状及各维度长度
print(
    f"数组:\n{a}, shape={a.shape}, len(a)={len(a)}, len(a[0])={len(a[0])}, len(a[0, 0])={len(a[0, 0])}"
)

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), len(a)=2, len(a[0])=3, len(a[0, 0])=4


## 2. 改变数组形状

### 2.1. `.reshape` 方法

#### 2.1.1. 指定目标形状元组

可以通过 `.reshape` 方法改变数组的形状, `.reshape` 方法会返回一个原数组的视图, 改变原数组的形状不会改变原数组的数据

例如: 将形状为 `(24,)` 的一维数组改为形状为 `(2, 12)` 的二维数组

In [4]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 12) 的二维数组
# 通过返回数组的 .base 属性可知, 结果数组是建立在原数组上的视图
b = a.reshape(2, 12)
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)


再例如: 将形状为 `(24,)` 的一维数组改为形状为 `(2, 3, 4)` 的三维数组

In [5]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 3, 4) 的三维数组
b = a.reshape(2, 3, 4)
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


注意: 在改变形状时, 新的形状所需的元素总数必须和原始形状所需的元素总数相同, 否则会抛出异常

下面的例子试图将一个形状为 `(23,)` 的数组改变为形状为 `(2, 3, 4)` 的数组, 由于 `2 x 3 x 4 = 24`, 共需 24 个元素, 而原始数组中只有 23 个元素, 所以会抛出异常, 形状转换失败

In [6]:
# 创建一个一维数组
a = np.arange(1, 24)

try:
    # 尝试将一维数组的形状改为 (2, 3, 4) 的三维数组, 因为数组元素数量与形状不符，抛出异常
    a.reshape(2, 3, 4)
except ValueError as e:
    print(f"{co.Fore.RED}错误: {e}{co.Style.RESET_ALL}")

错误: cannot reshape array of size 23 into shape (2,3,4)


#### 2.1.2. `.reshape` 方法的形状占位

如果数组的元素总数可以满足新形状所需的数组元素总数, 则调用 `.reshape` 方法时, 指定的形状元组的某个轴的值可以为 `-1`, Numpy 会自动计算该轴的值

例如: 将一维数组的形状改为 `(2, -1)`, 实际结果数组的形状为 `(2, 12)`

In [7]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, -1) 的二维数组, 实际形状为 (2, 12)
b = a.reshape(2, -1)
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)


再例如: 将一维数组的形状改为 `(2, 3, -1)`, 实际结果数组的形状为 `(2, 3, 4)`

In [8]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 3, -1) 的三维数组, 实际形状为 (2, 3, 4)
b = a.reshape(2, 3, -1)
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


目标形状的元组中, 任意轴的值都可以为 `-1`, 但只能有一个轴的值为 `-1`

In [9]:
# 创建一个一维数组
a = np.arange(1, 25)

b = a.reshape(-1, 3, 4)
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


如果目标形状元组中, 值为 `-1` 的轴数量大于一个, 则会抛出异常

In [10]:
# 创建一个一维数组
a = np.arange(1, 25)

try:
    # 在改变形状时, 目标形状元组中包含多个值为 -1 的轴, 会导致抛出异常
    a.reshape(-1, 3, -1)
except ValueError as e:
    print(f"{co.Fore.RED}错误: {e}{co.Style.RESET_ALL}")

错误: can only specify one unknown dimension


### 2.2. `np.reshape` 方法

除了使用数组对象的 `.reshape` 方法外, 还可以使用全局方法 `np.reshape`, 两个方法的作用类似

In [11]:
# 创建一个一维数组
a = np.arange(1, 25)

# 调用 np.reshape 方法改变原数组的形状, 返回原数组的新视图
b = np.reshape(a, (-1, 3, 4))
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n改变形状为\n{b}, shape={b.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变形状为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


## 3. 改变数组大小

除了改变数组的形状外, 还可以改变数组的总元素个数, 即数组的大小

### 3.1. `.resize` 方法

数组对象的 `.resize` 方法可以改变原数组的大小

注意: 数组对象的 `.resize` 方法改变的是原数组, 而不是返回原数组视图, 这一点和 `.reshape` 方法是截然不同的

与数组对象的 `.reshape` 方法不同, 对于 `.resize` 方法, 如果新形状大于原形状, 则会填充新元素, 如果小于原形状, 则会截断已有元素

#### 3.1.1. 改变数组形状

如果数组形状改变前后的元素总数不变, 则数组对象的 `.resize` 方法和 `.reshape` 方法的效果类似, 只是后者返回数组的视图 (即不对原数组做改变), 前者在数组本身进行操作

例如: 将形状为 `(24,)` 的一维数组改为形状为 `(2, 12)` 的二维数组

In [12]:
# 创建一个一维数组
a = np.arange(1, 25)
a_back = a.copy()

# 对原数组的形状进行改变
a.resize((2, 12))

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变大小为
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)


再例如: 将形状为 `(24,)` 的一维数组改为形状为 `(2, 3, 4)` 的三维数组

In [13]:
# 创建一个一维数组
a = np.arange(1, 25)
a_back = a.copy()

# 对原数组的形状进行改变
a.resize((2, 3, 4))

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)
改变大小为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


注意: 另一个和 `.reshape` 方法不同的是, `.resize` 方法的形状参数元组中, 不允许值为 `-1` 的轴, 因为 `.resize` 方法不仅会改变原数组的形状, 同时也可以改变其总元素个数

In [14]:
# 创建一个一维数组
a = np.arange(1, 25)

try:
    # 对原数组的形状进行改变
    a.resize((2, 3, -1))
except ValueError as e:
    print(f"{co.Fore.RED}错误: {e}{co.Style.RESET_ALL}")

错误: negative dimensions not allowed


#### 3.1.2. 改变数组大小

可以通过 `.resize` 方法同时改变数组的形状和数据大小

如果目标形状所需的总元素数量更多, 则进行填充, 以补充多余的元素值

例如: 将形状为 `(6,)` 的一维数组转换为形状为 `(12,)` 的一维数组

In [15]:
# 创造一个形状为 (6,) 的一维数组
a = np.arange(1, 7)
a_back = a.copy()

# 将其改变为形状为 (12,) 的一维数组, 目标形状需要 12 个元素
# 这一步会导致无法在原数组内存范围内完成操作, 需要创建新的数组对象, 所以 refcheck 参数必须设置为 False, 否则会引发异常
a.resize((12,), refcheck=False)

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[1 2 3 4 5 6], shape=(6,)
改变大小为
[1 2 3 4 5 6 0 0 0 0 0 0], shape=(12,)


注意: 这里使用了 `.resize` 方法的 `refcheck` 参数, 将其设置为了 `False`, 表示不检查原数组的被引用情况

如果 `refcheck` 参数设置为 `True`, 则如下情况会报错:

- 原数组被其它视图所引用, 例如原数组被切片、转置、转置的切片所引用
- 原数组所在的内存区域需要改变

当改变原数组的大小是, 就触发了上述第二个情况, 如果不将 `refcheck` 参数设置为 `False`, 则会报错, 但如果简单的对所有情况都将 `refcheck` 参数设置为 `False`, 则有可能会导致内存泄漏, 此时推荐使用 `np.resize` 方法来改变数组的大小

再例如: 将形状为 `(6,)` 的一维数组转换为形状为 `(2, 6)` 的二维数组

In [16]:
# 创造一个形状为 (6,) 的一维数组
a = np.arange(1, 7)
a_back = a.copy()

# 将其改变为形状为 (12,) 的一维数组, 目标形状需要 12 个元素
# 这一步会导致无法在原数组内存范围内完成操作, 需要创建新的数组对象, 所以 refcheck 参数必须设置为 False, 否则会引发异常
a.resize((12,), refcheck=False)

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[1 2 3 4 5 6], shape=(6,)
改变大小为
[1 2 3 4 5 6 0 0 0 0 0 0], shape=(12,)


再例如: 将形状为 `(4,)` 的一维数组转化为形状为 `(2, 3, 4)` 的三维数组

In [17]:
# 创造一个形状为 (4,) 的一维数组
a = np.arange(1, 7)
a_back = a.copy()

# 将其改变为形状为 (2, 3, 4) 的三维数组, 目标形状需要 24 个元素
a.resize((2, 3, 4), refcheck=False)

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[1 2 3 4 5 6], shape=(6,)
改变大小为
[[[1 2 3 4]
  [5 6 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(2, 3, 4)


如果目标形状的总元素数小于原数组形状的总元素数, 则会对原数组进行截取

注意, 此时也需要将 `.resize` 方法的 `refcheck` 参数设置为 `False`, 否则也会导致异常

例如: 将形状为 `(12,)` 的一维数组转换为形状为 `(6,)` 的一维数组

In [18]:
# 创造一个形状为 (13,) 的一维数组
a = np.arange(1, 13)
a_back = a.copy()

# 将其改变为形状为 (6,) 的一维数组, 目标形状需要 6 个元素
# 这一步会导致无法在原数组内存范围内完成操作, 需要创建新的数组对象, 所以 refcheck 参数必须设置为 False, 否则会引发异常
a.resize((6,), refcheck=False)

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,)
改变大小为
[1 2 3 4 5 6], shape=(6,)


再例如: 将形状为 `(2, 8)` 的二维数组改为形状为 `(3, 4)` 的二维数组

In [19]:
# 创造一个形状为 (16,) 的一维数组, 并将其改变为形状为 (2, 8) 二维数组
a = np.arange(1, 17)
a.resize((2, 8))

a_back = a.copy()

# 将数组改变为形状为 (3, 4) 的二维数组, 目标形状需要 12 个元素
a.resize((3, 4), refcheck=False)

print(f"将数组\n{a_back}, shape={a_back.shape}\n改变大小为\n{a}, shape={a.shape}")

将数组
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]], shape=(2, 8)
改变大小为
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4)


### 3.2. `np.resize` 方法

更推荐使用 `np.resize` 方法来改变数组的大小, 而非直接使用数组对象的 `.resize` 方法, 原因如下:

- `np.resize` 方法会返回一个新的数组对象, 而不是改变原数组对象, 因此 `np.resize` 方法更安全, 也无需进行引用检查
- `np.resize` 方法会通过数组原有元素值循环填充缺失的数据, 而不是使用默认值

例如: 将形状为 `(4,)` 的一维数组转换为形状为 `(2, 6)` 的二维数组

In [20]:
# 创建形状为 (4,) 的一维数组对象
a = np.arange(1, 5)

# 改变数组的大小, 将形状为 (4,) 的一维数组改为形状为 (2, 6) 的二维数组
# 此时会返回一个新数组对象, 新数组额外的元素值通过原数组原有元素值循环填充
b = np.resize(a, (2, 6))
assert not (b is a)

print(f"将数组\n{a}, shape={a.shape}\n改变大小为\n{b}, shape={b.shape}")

将数组
[1 2 3 4], shape=(4,)
改变大小为
[[1 2 3 4 1 2]
 [3 4 1 2 3 4]], shape=(2, 6)


再例如: 将形状为 `(4, 8)` 的二维数组转换为形状为 `(2, 3, 4)` 的三维数组

In [21]:
# 创建形状为 (4, 8) 的一维数组对象
a = np.arange(1, 33)
a.resize((4, 8))

# 改变数组的大小, 将形状为 (4,) 的一维数组改为形状为 (2, 6) 的二维数组
# 此时会返回一个新数组对象, 新数组额外的元素值通过原数组原有元素值循环填充
b = np.resize(a, (2, 3, 4))
assert not (b is a)

print(f"将数组\n{a}, shape={a.shape}\n改变大小为\n{b}, shape={b.shape}")

将数组
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]], shape=(4, 8)
改变大小为
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


## 4. 展平数组

可以将多维数组 (二维以上) 转化为一维数组

### 4.1. 通过 `.reshape` 方法

最简单的方式即通过数组对象的 `.reshape` 方法, 并传递新的形状参数 `(-1,)`, 这样无论原数组是什么形状, 都会得到一个包含原数组全部元素的一维数组视图

In [22]:
# 定义一个形状为 (2, 2, 3) 的三维数组
a = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ],
    ]
)

# 将原数组的形状改为 (-1,), 即将数组变为一维
# 这个过程不会产生新的数组对象, 而是得到原数组的新视图
b = a.reshape((-1,))
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n展平后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)
展平后为
[ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,)


### 4.2. `.ravel` 方法

数组对象的 `.ravel` 方法返回数组的一个一维视图, 其效果和通过 `.reshape((-1,))` 获取一个一维数组一致的

In [23]:
# 定义一个形状为 (2, 2, 3) 的三维数组
a = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ],
    ]
)

# 通过 .ravel 方法获取数组的视图, 该视图的形状为 (12,)
# 该过程不会产生新的数组对象, 只是基于原数组创建一个视图
b = a.ravel()
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n展平后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)
展平后为
[ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,)


### 4.3. `.flatten` 方法

In [24]:
# 定义一个形状为 (2, 2, 3) 的三维数组
a = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ],
    ]
)

# 通过 .flatten 方法获取数组的副本, 该副本形状为 (12,), 即已被展平
# 该过程会产生原数组的副本, 即展平的数组为一个新数组对象
b = a.flatten()
assert b.base is None

print(f"将数组\n{a}, shape={a.shape}\n展平后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)
展平后为
[ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,)


## 5. 数组转置

### 5.1. `T` 转置

转置数组表示沿原数组的某个轴对数组元素进行旋转, 从而得到的新数组, 例如:

对于矩阵
$A = \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
\end{bmatrix}$, 其转置矩阵为
$A^T = \begin{bmatrix}
    1 & 4 \\
    2 & 5 \\
    3 & 6 \\
\end{bmatrix}$

转置除了会改变数组的形状外, 数组转置前后还具备元素位置的旋转关系

转置其是线性代数的一个重要概念, 及将 $m \times n$ 矩阵转置为 $n \times m$ 矩阵, 矩阵中元素的位置关系不变

对于一维数组, 其转置数组仍为一维数组, 和原数组一致, 例如:

In [25]:
# 创建一维数组
a = np.array([1, 2, 3, 4, 5])

# 获取一维数组的转置数组, 结果和原数组一致
b = a.T
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[1 2 3 4 5], shape=(5,)
转置后为
[1 2 3 4 5], shape=(5,)


转置本质上是数组 "轴" 的交换, 如上述的二维数组 $A = \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
\end{bmatrix}$, 其转置即表示将数组的 `x` 轴和 `y` 轴交换 (通俗的说, 即 `x` 轴变为列, `y` 轴变为行), 可得到 $A^T = \begin{bmatrix}
    1 & 4 \\
    2 & 5 \\
    3 & 6 \\
\end{bmatrix}$

例如如下形状为 `(2, 3)` 的二维数组转置为形状为 `(3, 2)` 的二维数组

In [26]:
# 创建形状为 (2, 3) 的二维数组
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# 获取二维数组的转置数组, 结果为一个形状为 (3, 2) 的二维数组
b = a.T
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[[1 2 3]
 [4 5 6]], shape=(2, 3)
转置后为
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2)


对于更高维度的数组 (二维以上) 即将所有的轴反转, 例如将 `x`, `y` 和 `z` 轴交换为 `z`, `y`, `x` 轴

例如如下形状为 `(2, 3, 4)` 的三维数组转置为形状为 `(4, 3, 2)` 的三维数组

In [27]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.arange(1, 25)
a.resize(2, 3, 4)

# 获取三维数组的转置数组, 结果为一个形状为 (4, 3, 2) 的三维数组
b = a.T
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
转置后为
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)


下面的代码展示了如何通过元素索引值的映射改变数组的轴顺序, 将轴顺序由 `x, y, z` 改为 `z, y, x`

In [28]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.arange(1, 25)
a.resize(2, 3, 4)

# 创建一个形状为 (4, 3, 2) 的数组, 作为存放转置后元素的数组
b = np.zeros((4, 3, 2), dtype=a.dtype)

# 遍历元素组的各元素, 并将其安装新的轴顺序存入目标数组中, 完成转置
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
        for z in range(a.shape[2]):
            b[z, y, x] = a[x, y, z]

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
转置后为
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)


### 5.2. `.transpose` 方法

和 `T` 转置不同, 数组对象的 `.transpose` 方法允许指定数组轴的排列顺序, 例如将 `x`, `y`, `z` 三个轴的顺序改为 `y`, `x`, `z`

Numpy 中用 `0`, `1`, `2`, `...` 表示轴, 其中 `0` 表示第一个轴 (相当于 `x` 轴), `1` 表示第二个轴 (相当于 `y` 轴), `2` 表示第三个轴 (相当于 `z` 轴), 以此类推

In [29]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.arange(1, 25)
a.resize(2, 3, 4)

# 将数组的轴按照 (1, 0, 2) 的顺序进行重新排列, 结果为一个形状为 (3, 2, 4) 的三维数组
# 即将第一轴和第二轴互换
b = a.transpose((1, 0, 2))
assert b.base is a

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
转置后为
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]], shape=(3, 2, 4)


上面的转置的具体计算过程如下:

In [30]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.arange(1, 25)
a.resize(2, 3, 4)

# 创建一个形状为 (4, 3, 2) 的数组, 作为存放转置后元素的数组
b = np.zeros((3, 2, 4), dtype=a.dtype)

# 遍历元素组的各元素, 并将其安装新的轴顺序存入目标数组中, 完成转置
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
        for z in range(a.shape[2]):
            b[y, x, z] = a[x, y, z]

print(f"将数组\n{a}, shape={a.shape}\n转置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
转置后为
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]], shape=(3, 2, 4)


可以认为 `T` 转置就是 `.transpose` 方法转置的特例, `T` 转置相当于把数组所有轴的顺序反过来后的结果, 例如:

二维数组的 `T` 转置等价于将轴 `(0, 1)` 变为 `(1, 0)`

In [31]:
# 创建形状为 (2, 3) 的二维数组
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# 获取数组的 T 转置
b = a.T

# 转置, 将 (0, 1) 轴转为 (1, 0) 轴
c = a.transpose((1, 0))

print(
    f"数组\n{a}, shape={a.shape}\n的 T 转置为\n{b}, shape={b.shape}\ntranspose((1, 0)) 转置为\n{c}, shape={c.shape}"
)

数组
[[1 2 3]
 [4 5 6]], shape=(2, 3)
的 T 转置为
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2)
transpose((1, 0)) 转置为
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2)


三维数组的 `T` 转置等价于

In [32]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24],
        ],
    ]
)

# 获取数组的 T 转置
b = a.T

# 转置, 将 (0, 1, 2) 轴转为 (2, 1, 0) 轴
c = a.transpose((2, 1, 0))

print(
    f"数组\n{a}, shape={a.shape}\n的 T 转置为\n{b}, shape={b.shape}\ntranspose((2, 1, 0)) 转置为\n{c}, shape={c.shape}"
)

数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
的 T 转置为
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)
transpose((2, 1, 0)) 转置为
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)


### 5.3 `.swapaxes` 方法

数组对象的 `.swapaxes` 方法用于交换数组的两个轴

例如交换二维数组的 `(0, 1)` 两个轴, 即将其转化为 `(1, 0)` 轴, 相当于对二维数组进行 `T` 转置

In [33]:
# 创建形状为 (2, 3) 的二维数组
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# 将数组的 (0, 1) 轴进行交换
b = a.swapaxes(0, 1)

print(f"将数组\n{a}, shape={a.shape}\n的轴 0, 1 交换后为\n{b}, shape={b.shape}")

将数组
[[1 2 3]
 [4 5 6]], shape=(2, 3)
的轴 0, 1 交换后为
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2)


再例如, 交换三维数组的第一个和第三个轴, 即将 `(0, 1, 2)` 轴变为 `(2, 0, 1)` 轴, 相当于对三维数组进行 `T` 转置

In [34]:
# 创建形状为 (2, 3, 4) 的二维数组
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24],
        ],
    ]
)


# 将数组的 (0, 2) 轴进行交换
b = a.swapaxes(0, 2)

print(f"将数组\n{a}, shape={a.shape}\n的轴 0, 2 交换后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
的轴 0, 2 交换后为
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)


### 5.4 `np.moveaxis` 方法

`np.moveaxis` 方法用于将数组的轴移动到新的位置, 而其他轴则保持原来的顺序

对于形状为 `(2, 3, 4)` 的三维数组, 移动轴 0 到轴 1 的位置后, 数组变为 `(3, 2, 4)`, 移动轴 1 到轴 2 的位置后, 数组变为 `(3, 4, 2)`

例如: 一次移动一个轴, 将

In [35]:
# 创建形状为 (2, 3, 4) 的三维数组
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24],
        ],
    ]
)


# 将数组的轴 0 移动到轴 2 的位置, 其余轴顺序不变, 即将数组的形状中的 2 移动到 4 之后, 数组形状变为 (3, 4, 2)
b = np.moveaxis(a, 0, 2)

print(f"将数组\n{a}, shape={a.shape}\n的 0 轴移动到 1 轴的位置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
的 0 轴移动到 1 轴的位置后为
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]], shape=(3, 4, 2)


再例如: 同时移动数组的 0 轴和 1 轴， 将其移动到 1 轴和 2 轴的位置

In [36]:
# 创建形状为 (2, 3, 4) 的二维数组
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24],
        ],
    ]
)


# 同时将数组的 0 轴和 1 轴移动到 1 轴和 2 轴的位置
# 即将数组形状的 2 和 3 移动到 3 和 4 的位置, 故数组形状变为 (4, 2, 3)
b = np.moveaxis(a, (0, 1), (1, 2))

print(f"将数组\n{a}, shape={a.shape}\n的 0, 1 轴移动到 1, 2 轴的位置后为\n{b}, shape={b.shape}")

将数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
的 0, 1 轴移动到 1, 2 轴的位置后为
[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]], shape=(4, 2, 3)


## 6. 改变数组的维度

### 6.1. `np.expand_dims` 方法

通过 `np.expand_dims` 方法可以在已有数组中添加一个维度

新添加的维度的长度为 `1`, 可在添加维度后可进一步为改维度添加元素

注意: `np.expand_dims` 方法不会创建新的数组对象, 而是返回原数组对象的视图对象

另外, 通过数组对象的 `.reshape` 方法也可以做到 `np.expand_dims` 方法一致的结果, 但 `.reshape` 方法需要在当前形状基础上增加一个

#### 6.1.1. 在现有维度前后增加维度

例如: 对于形状为 `(4,)` 的一维数组, 在其轴 0 的位置上插入一个新维度, 让数组形状变为 `(1, 4)`

In [37]:
# 创建一个形状为 (4,) 的一维数组
a = np.array([1, 2, 3, 4])

# 在数组轴 0 的位置插入新维度, 令数组形状变为 (1, 4)
b = np.expand_dims(a, axis=0)

print(f"在数组\n{a}, shape={a.shape}\n的维度前插入新维度后: \n{b}, shape={b.shape}， base={b.base is a}")

# 在数组的 0 轴上添加一组元素, 另数组形状变为 (2, 4)
c = np.append(b, [[5, 6, 7, 8]], axis=0)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[1 2 3 4], shape=(4,)
的维度前插入新维度后: 
[[1 2 3 4]], shape=(1, 4)， base=True
在数组轴 1 上添加元素后 
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)


上述代码也可以通过 `.reshape` 方法来实现

In [38]:
# 创建一个形状为 (4,) 的一维数组
a = np.array([1, 2, 3, 4])

# 改变数组形状, 令数组形状变为 (1, 4)
b = a.reshape((1, -1))

print(
    f"在数组\n{a}, shape={a.shape}\n的维度前插入新维度后: \n{b}, shape={b.shape}"
)

# 在数组的 0 轴上添加一组元素, 另数组形状变为 (2, 4)
c = np.append(b, [[5, 6, 7, 8]], axis=0)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[1 2 3 4], shape=(4,)
的维度前插入新维度后: 
[[1 2 3 4]], shape=(1, 4)
在数组轴 1 上添加元素后 
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)


例如: 对于形状为 `(4,)` 的一维数组, 在其轴 1 的位置上插入一个新维度, 让数组形状变为 `(4, 1)`

In [39]:
# 创建一个形状为 (4,) 的一维数组
a = np.array([1, 2, 3, 4])

# 在数组轴 1 的位置插入新维度, 另数组形状变为 (4, 1)
b = np.expand_dims(a, axis=1)

print(f"在数组\n{a}, shape={a.shape}\n的维度前插入新维度后: \n{b}, shape={b.shape}")

# 在数组的 1 轴上添加一组元素, 另数组形状变为 (4, 2)
c = np.append(b, [[5], [6], [7], [8]], axis=1)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[1 2 3 4], shape=(4,)
的维度前插入新维度后: 
[[1]
 [2]
 [3]
 [4]], shape=(4, 1)
在数组轴 1 上添加元素后 
[[1 5]
 [2 6]
 [3 7]
 [4 8]], shape=(4, 2)


上述代码也可以通过 `.reshape` 方法来实现

In [40]:
# 创建一个形状为 (4,) 的一维数组
a = np.array([1, 2, 3, 4])

# 改变数组形状, 另数组形状变为 (4, 1)
b = a.reshape((-1, 1))

print(f"在数组\n{a}, shape={a.shape}\n的维度前插入新维度后: \n{b}, shape={b.shape}")

# 在数组的 1 轴上添加一组元素, 另形状变为 (4, 2)
c = np.append(b, [[5], [6], [7], [8]], axis=1)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[1 2 3 4], shape=(4,)
的维度前插入新维度后: 
[[1]
 [2]
 [3]
 [4]], shape=(4, 1)
在数组轴 1 上添加元素后 
[[1 5]
 [2 6]
 [3 7]
 [4 8]], shape=(4, 2)


注意, 新的维度只能在数组现有维度前后插入, 否则会抛出异常

In [41]:
# 创建一个形状为 (4,) 的一维数组
a = np.array([1, 2, 3, 4])

try:
    # 尝试扩展维度, 但一维数组前后只有 0 和 1 两个轴, 无法直接扩展 2 轴, 故抛出异常
    np.expand_dims(a, axis=2)
except ValueError as e:
    print(f"{co.Fore.RED}异常: {e}{co.Fore.RESET}")

异常: axis 2 is out of bounds for array of dimension 2


#### 6.1.2. 在现有维度中间插入维度

In [42]:
# 创建一个形状为 (2, 3) 的二维数组
a = np.array(
    [
        [1, 2, 3],
        [7, 8, 9],
    ]
)

# 在数组的第 1 轴位置, 插入一个长度为 1 的维度, 另数组形状变为 (2, 1, 3)
b = np.expand_dims(a, axis=1)

print(f"在数组\n{a}, shape={a.shape}\n的维度中间插入新维度后: \n{b}, shape={b.shape}")

# 为数组的 1 轴添加一组元素, 另数组形状变为 (2, 2, 3)
c = np.append(b, [[[4, 5, 6]], [[10, 11, 12]]], axis=1)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[[1 2 3]
 [7 8 9]], shape=(2, 3)
的维度中间插入新维度后: 
[[[1 2 3]]

 [[7 8 9]]], shape=(2, 1, 3)
在数组轴 1 上添加元素后 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)


上述代码也可以通过 `.reshape` 方法来实现, 此时可体现出 `.reshape` 方法和 `np.expand_dims` 方法的区别: `.reshape` 方法需要明确设置数组未来的形状, 故需要知道数组原本的形状, 而 `np.expand_dims` 方法只需要确定插入新轴的位置即可, 无需知道数组之前的形状

In [43]:
# 创建一个形状为 (2, 3) 的二维数组
a = np.array(
    [
        [1, 2, 3],
        [7, 8, 9],
    ]
)

# 改变数组形状, 另数组形状变为 (2, 1, 3)
b = a.reshape((2, 1, -1))

print(f"在数组\n{a}, shape={a.shape}\n的维度中间插入新维度后: \n{b}, shape={b.shape}")

# 为数组的 1 轴添加一组元素, 另数组形状变为 (2, 2, 3)
c = np.append(b, [[[4, 5, 6]], [[10, 11, 12]]], axis=1)
print(f"在数组轴 1 上添加元素后 \n{c}, shape={c.shape}")

在数组
[[1 2 3]
 [7 8 9]], shape=(2, 3)
的维度中间插入新维度后: 
[[[1 2 3]]

 [[7 8 9]]], shape=(2, 1, 3)
在数组轴 1 上添加元素后 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3)


### 6.2. `.squeeze` 方法