# 数组形状

In [31]:
import numpy as np
import colorama as co

数组形状用于表示数组的维度和各维度的长度

数组形状是一个元组, 元素的个数表示数组的维数, 元素的值表示对应维的长度

## 1. 改变数组形状

### 1.1. `.shape` 属性

可以通过数组对象的 `.shape` 属性获取数组的形状

一维数组形状

In [32]:
# 创建一维数组
a = np.array([1, 2, 3, 4, 5])

# 获取数组形状, 一维数组的形状为只有一项的元组, 元组元素值为数组长度
print(f"数组: {a}, shape={a.shape}, len(a)={len(a)}")

数组: [1 2 3 4 5], shape=(5,), len(a)=5


多维数组形状

In [33]:
# 创建一个三维数组
a = np.arange(1, 25).reshape(2, 3, 4)

# 输出数组的形状及各维度长度
print(
    f"数组:\n{a}\nshape={a.shape}, len(a)={len(a)}, len(a[0])={len(a[0])}, len(a[0, 0])={len(a[0, 0])}"
)

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape=(2, 3, 4), len(a)=2, len(a[0])=3, len(a[0, 0])=4


### 1.2. 改变数组形状

可以通过 `.reshape` 方法改变数组的形状, `.reshape` 方法会返回一个原数组的视图, 改变原数组的形状不会改变原数组的数据

对于一个形状为 `(24,)` 的一维数组

In [34]:
# 创建一个一维数组
a = np.arange(1, 25)

print(f"数组:\n{a}, shape={a.shape}")

数组:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)


将一维数组的形状改为 `(2, 12)` 的二维数组

In [35]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 12) 的二维数组
b = a.reshape(2, 12)

print(f"改变数组形状为二维数组:\n{b}, shape={b.shape}")

改变数组形状为二维数组:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)


将一维数组的形状改为 `(2, 3, 4)` 的三维数组

In [36]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 3, 4) 的三维数组
b = a.reshape(2, 3, 4)

print(f"改变数组形状为三维数组:\n{b}, shape={b.shape}")

改变数组形状为三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


注意, 在改变形状时, 新的形状所需的元素总数必须和原始形状所需的元素总数相同, 否则会抛出异常

下面的例子试图将一个形状为 `(23,)` 的数组改变为形状为 `(2, 3, 4)` 的数组, 由于 2 x 3 x 4 = 24, 共需 24 个元素, 而原始数组中只有 23 个元素, 所以会抛出异常, 形状转换失败

In [37]:
# 创建一个一维数组
a = np.arange(1, 24)

try:
    # 尝试将一维数组的形状改为 (2, 3, 4) 的三维数组, 因为数组元素数量与形状不符，抛出异常
    a.reshape(2, 3, 4)
except ValueError as e:
    print(f"{co.Fore.RED}错误: {e}{co.Style.RESET_ALL}")

错误: cannot reshape array of size 23 into shape (2,3,4)


### 1.3. `.reshape` 方法的形状占位

如果数组的元素总数可以满足新形状所需的数组元素总数, 则调用 `.reshape` 方法时, 指定的形状元组的某个轴的值可以为 `-1`, Numpy 会自动计算该轴的值

将一维数组的形状改为 `(2, -1)`, 实际结果数组的形状为 `(2, 12)`

In [38]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, -1) 的二维数组, 实际形状为 (2, 12)
b = a.reshape(2, -1)

print(f"改变数组形状为二维数组:\n{b}, shape={b.shape}")

改变数组形状为二维数组:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)


将一维数组的形状改为 `(2, 3, -1)`, 实际结果数组的形状为 `(2, 3, 4)`

In [39]:
# 创建一个一维数组
a = np.arange(1, 25)

# 将一维数组的形状改为 (2, 3, -1) 的三维数组, 实际形状为 (2, 3, 4)
b = a.reshape(2, 3, -1)

print(f"改变数组形状为三维数组:\n{b}, shape={b.shape}")

改变数组形状为三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


In [ ]:
# 创建一个一维数组
a = np.arange(1, 25)

try:
    # 尝试将一维数组变为3x3x3
    a.reshape(2, -1, 3)
except ValueError as e:
    print("无法重塑为3x3x3:", e)