# 数组形状

In [6]:
import numpy as np

数组形状用于表示数组的维度和各维度的长度

数组形状是一个元组, 元素的个数表示数组的维数, 元素的值表示对应维的长度

## 1. `.shape` 属性

可以通过数组对象的 `.shape` 属性获取数组的形状

一维数组形状

In [11]:
# 创建一维数组
a = np.array([1, 2, 3, 4, 5])

# 获取数组形状, 一维数组的形状为只有一项的元组, 元组元素值为数组长度
print(f"数组: {a}, shape={a.shape}, len(a)={len(a)}")

数组: [1 2 3 4 5], shape=(5,), len(a)=5


多维数组形状

In [ ]:
# 创建一个三维数组
a = np.arange(1, 25).reshape(2, 3, 4)

# 输出数组的形状及各维度长度
print(
    f"数组:\n{a}\nshape={a.shape}, len(a)={len(a)}, len(a[0])={len(a[0])}, len(a[0, 0])={len(a[0, 0])}"
)

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape=(2, 3, 4), len(a)=2, len(a[0])=3, len(a[0, 0])=4
