# 数组元素类型

In [10]:
import numpy as np

## 1. dtype 类型

Numpy 通过数组的 `dtype` 属性来控制

In [ ]:
dt = np.dtype(np.int32)

## 1. 内置类型

Numpy 库中内置了一系列表示数组元素类型的标识，如:
- `np.int8`
- `np.int16`
- `np.int32`
- `np.int64`
- `np.uint8`
- `np.uint16`
- `np.uint32`
- `np.uint64`
- `np.float16`
- `np.float32`
- `np.float64`
- `np.complex64`
- `np.complex128`
等

不同类型表示数组元素的字节长度, 也即定义了数组元素的数值范围, 数值精度

### 1.1. 创建数组时指定类型

可以在创建数组时, 通过 `dtype` c创建指定数组元素的类型, 默认会自动通过创建数组时所给的元素值进行类型推导

如果的 `dtype` 参数指定的数组元素类型于创建数组所给的数组元素类型不一致, 则 Numpy 会自动将元素值进行类型转换 (例如将 `int` 转换为 `float`)

In [11]:
a = np.array([1, 2, 3, 4], dtype=np.int32)
print(f"> 数组:\n{a}, dtype={a.dtype}")

a = np.array(a / 10.0, dtype=np.float64)
print(f"> 数组:\n{a}, dtype={a.dtype}")

> 数组:
[1 2 3 4], dtype=int32
> 数组:
[0.1 0.2 0.3 0.4], dtype=float64


### 1.2. 改变数组的元素类型

通过数组对象的 `astype` 方法, 可以将数组的元素类型转换成指定的其它类型

注意, 这里的类型转换并不是简单的修改数组元素的内存占用, 而是根据 Numpy 的规则进行, 例如 `int32` 值 `10` 转换为 `str_` 类型值为 `'10'`

In [ ]:
a = np.array([1, 2, 3, 4], dtype=np.uint32)
print(f"> 数组:\n{a}, dtype={a.dtype}")

a = a.astype(np.float32)
print(f"> 数组:\n{a}, dtype={a.dtype}")

a = a.astype(np.str_)
print(f"> 数组:\n{a}, dtype={a.dtype}")

a = a.astype(np.dtypes.StringDType)
print(f"> 数组:\n{a}, dtype={a.dtype}")

> 数组:
[1 2 3 4], dtype=uint32
> 数组:
[1. 2. 3. 4.], dtype=float32
> 数组:
['1.0' '2.0' '3.0' '4.0'], dtype=<U32
> 数组:
['1.0' '2.0' '3.0' '4.0'], dtype=StringDType()


### 1.3. 类型名称

除通过 Numpy 内置的类型标识外, 还可以通过字符串名称来指定数组的 `dtype` 属性, 且可指定

#### 1.3.1. 整数类型名称

In [ ]:
s = np.array([1, 2, 3, 4])

for dt in [2, 4, 8]:
    a = s.astype(f"i{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    a = s.astype(f"<i{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    a = s.astype(f">i{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    print()

> 数组: [1 2 3 4], dtype = int16
> 数组: [1 2 3 4], dtype = int16
> 数组: [1 2 3 4], dtype = >i2

> 数组: [1 2 3 4], dtype = int32
> 数组: [1 2 3 4], dtype = int32
> 数组: [1 2 3 4], dtype = >i4

> 数组: [1 2 3 4], dtype = int64
> 数组: [1 2 3 4], dtype = int64
> 数组: [1 2 3 4], dtype = >i8



#### 1.3.2. 浮点数类型名称

In [64]:
s = np.array([1, 2, 3, 4]) / 10.0

for dt in [2, 4, 8, 16]:
    a = s.astype(f"f{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    a = s.astype(f"<f{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    a = s.astype(f">f{dt}")
    print(f"> 数组: {a}, dtype = {a.dtype}")

    print()

> 数组: [0.1 0.2 0.3 0.4], dtype = float16
> 数组: [0.1 0.2 0.3 0.4], dtype = float16
> 数组: [0.1 0.2 0.3 0.4], dtype = >f2

> 数组: [0.1 0.2 0.3 0.4], dtype = float32
> 数组: [0.1 0.2 0.3 0.4], dtype = float32
> 数组: [0.1 0.2 0.3 0.4], dtype = >f4

> 数组: [0.1 0.2 0.3 0.4], dtype = float64
> 数组: [0.1 0.2 0.3 0.4], dtype = float64
> 数组: [0.1 0.2 0.3 0.4], dtype = >f8

> 数组: [0.1 0.2 0.3 0.4], dtype = float128
> 数组: [0.1 0.2 0.3 0.4], dtype = float128
> 数组: [0.1 0.2 0.3 0.4], dtype = >f16

