# 数组

首先, 导入 Numpy 模块

In [2]:
import numpy as np

## 1. 创建数组

### 1.1. 通过 Python 数组创建

In [3]:
# 通过一维 Python 数组创建 NumPy 数组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}")

# 通过二维 Python 数组创建 NumPy 数组
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\n二维数组内容:\n{data}")

# 通过三维 Python 列表创建 NumPy 数组
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1 2 3 4]

二维数组内容:
[[1 2 3 4]
 [5 6 7 8]]

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 1.2. 创建元素值为 `0` 的数组

In [4]:
# 创建元素值为 0 的一维数组
data = np.zeros(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 0 的二维数组
data = np.zeros(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 0 的三维数组
data = np.zeros(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[0. 0. 0. 0.]

二维数组内容:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

三维数组内容:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
# 创建元素值为 1 的一维数组
data = np.ones(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 1 的二维数组
data = np.ones(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 1 的三维数组
data = np.ones(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.3. 创建元素值为 "空" 的数组

通过 `np.empty` 函数创建一个元素值为 "空" 的数组

注意: 所谓元素值为 "空" 的数组，指的是直接分配内存, 且不会对元素所用内存进行初始化操作, 所以所分配内存中的内容是未知的 (或保留上次该区域内存使用的值)

所以创建了元素值为 "空" 的数组后, 必须对数组元素值全部进行初始化

对于已确定会对数组元素值进行全部初始化的场景, 通过 `np.empty` 函数创建数组可以提升程序效率

In [6]:
# 创建元素值未知的一维数组
data = np.empty(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值未知的二维数组
data = np.empty(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值未知的三维数组
data = np.empty(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.4. 创建元素值为连续序列的数组

In [7]:
data = np.linspace(1, 10, 10)
print(f"数组内容:\n{data}")

data = np.linspace(1, 10, 20)
print(f"\n数组内容:\n{data}")

数组内容:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

数组内容:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 1.5. 创建元素值为 `0`~`1` 随机数的数组

In [8]:
# 创建随机元素值的一维数组
data = np.random.rand(4)
print(f"数组内容:\n{data}")

# 创建随机元素值的二维数组
data = np.random.rand(3, 4)
print(f"\n数组内容:\n{data}")

# 创建随机元素值的三维数组
data = np.random.rand(2, 3, 4)
print(f"\n数组内容:\n{data}")

# `np.random.rand` 函数不能指定随机数范围, 只能生成 `0`~`1` 之间的随机数
# 要指定随机数范围, 可通过下面的计算方法
min_, max_ = 5, 10
data = min_ + (max_ - min_) * (np.random.rand(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[0.63194958 0.04778206 0.80668216 0.88051904]

数组内容:
[[0.34446426 0.10918339 0.60528533 0.94068266]
 [0.08355662 0.55015668 0.56689969 0.85104806]
 [0.96338608 0.85150671 0.96085044 0.16475745]]

数组内容:
[[[0.07112314 0.98221516 0.60943163 0.02051637]
  [0.00257159 0.39927238 0.54056019 0.17138874]
  [0.77837558 0.32288871 0.70466376 0.56552619]]

 [[0.86827277 0.27861351 0.09062541 0.52085231]
  [0.53332289 0.05783583 0.48990751 0.26907913]
  [0.65450107 0.4970348  0.69439988 0.56019749]]]

数组内容:
[[[7.67003343 9.02390697 7.52917739 6.591489  ]
  [7.13022126 5.48647197 7.29279577 7.59253054]
  [5.45756047 7.52788427 5.71572963 8.3908227 ]]

 [[5.69428135 8.30241477 8.78483425 5.64914007]
  [9.63584325 5.30139805 6.93664994 8.31403179]
  [9.50429843 6.89217262 6.52224209 5.35523825]]]


### 1.6. 创建元素值随机整数的数组

In [9]:
# 创建元素值为 `1`~`10` 之间随机数的一维数组
data = np.random.randint(1, 10, size=(4,))
print(f"数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的二维数组
data = np.random.randint(1, 10, size=(3, 4))
print(f"\n数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的三维数组
data = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[9 7 9 7]

数组内容:
[[4 5 9 1]
 [9 5 3 8]
 [8 1 7 8]]

数组内容:
[[[4 3 7 6]
  [4 7 1 9]
  [2 8 9 6]]

 [[7 7 7 7]
  [2 3 9 8]
  [4 2 9 9]]]


## 2. 数组属性

### 2.1. 数组维度 (`ndim`)

可以获取到一个数组包含的维度数

In [10]:
# 一维数组的 dim 总为 `1`
data = np.arange(1, 25)  # 创建一个包含 1 到 24 的一维数组
print(f"一维数组:\n{data}, dim={data.ndim}")

# 二维数组的 dim 总为 `2`
data = data.reshape(2, -1)
print(f"\n二维数组:\n{data}, dim={data.ndim}")

# 三维数组的 dim 总为 `3`
data = data.reshape(2, 3, -1)
print(f"\n三维数组:\n{data}, dim={data.ndim}")

一维数组:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], dim=1

二维数组:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], dim=2

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], dim=3


### 2.2. 数组形状 (`shape`)

数组的形状即数组在每个维度的长度, 例如 shape 为 `(2, 3)` 的数组, 表示一个有 `2` 行 `3` 列的二维数组

In [11]:
# 获取一维数组的形状, 结果为一个包含一个值的元组
data = np.array([1, 2, 3, 4])
print(f"一维数组:\n{data}, shape={data.shape}")

# 获取二维数组的形状, 结果为一个包含两个值的元组, 表示数组的两个维度
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组:\n{data}, shape={data.shape}")

# 获取三维数组的形状, 结果为一个包含三个值的元组, 描述数组的三个维度
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组:\n{data}, shape={data.shape}")

一维数组:
[1 2 3 4], shape=(4,)

二维数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4)

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


### 2.3. 数组长度 (`size`)

数组长度即数组包含的元素总数, 和数组的维度或数组的形状无关

In [12]:
data = np.array([1, 2, 3, 4])
print(f"一维数组:\n{data}, size={data.size}")

data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组:\n{data}, size={data.size}")

data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组:\n{data}, size={data.size}")

一维数组:
[1 2 3 4], size=4

二维数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], size=12

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], size=24


### 2.4. 数组元素类型 (`dtype`)

数组中的元素具备统一的数据类型, 可通过 `np.dtype` 查看, 可能的类型包括:

- `np.int8`: 8 位有符号整数
- `np.int16`: 16 位有符号整数
- `np.int32`: 32 位有符号整数
- `np.int64`: 64 位有符号整数
- `np.uint8`: 8 位无符号整数
- `np.uint16`: 16 位无符号整数
- `np.uint32`: 32 位无符号整数
- `np.uint64`: 64 位无符号整数
- `np.float16`: 16 位浮点数
- `np.float32`: 32 位浮点数
- `np.float64`: 64 位浮点数
- `np.complex64`: 64 位复数
- `np.complex128`: 128 位复数
- `np.bool_`: 布尔值

In [13]:
data = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(f"数组:\n{data}, dtype={data.dtype}")

data = data * np.array([0.01])
print(f"\n数组:\n{data}, dtype={data.dtype}")

data = np.array([n >= 0.1 for n in data.flat]).reshape(data.shape)
print(f"\n数组:\n{data}, dtype={data.dtype}")

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], dtype=int64

数组:
[[[0.01 0.02 0.03 0.04]
  [0.05 0.06 0.07 0.08]
  [0.09 0.1  0.11 0.12]]], dtype=float64

数组:
[[[False False False False]
  [False False False False]
  [False  True  True  True]]], dtype=bool


## 3. 改变数组的形状

In [14]:
# 定义一个 24 个元素的一维数组
data = np.arange(1, 25)
print(f"数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将一维数组改为二维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, -1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将二维数组改为三维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, 3, -1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将三维数组改为一维数组
data = data.reshape(-1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 如果目标形状无法达成 (及元素个数无法满足目标形状要求), 则操作失败
# data = data.reshape(2, 5, -1)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)


## 4. 数组转置

转置是线性代数的一个概念, 及将 $m \times n$ 矩阵转置为 $n \times m$ 矩阵, 矩阵中元素的位置关系不变, 例如:

对于矩阵
$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$, 其转置矩阵为
$
A^T=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}
$

Numpy 支持多维数组 (多维矩阵), 故可对多维数组进行转置, 例如对于三维数组, 可将 $m \times n \times k$ 矩阵转置为 $k \times n \times m$

In [15]:
data = np.arange(1, 25).reshape(2, 3, 4)
print(f"数组内容:\n{data}, shape={data.shape}")

data = data.T
print(f"\n转置后数组内容:\n{data}, shape={data.shape}")

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)

转置后数组内容:
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)


## 5. 切片

数组的切片用于从数组中切割出一个新数组, 可以通过 Python 元素的 `slice` 对象进行切片, 也可以通过 Numpy 特有的 `:` 语法进行切片 (由于 Numpy 对数组索引做了特殊定义, 所以通过 `:` 语法取代 Python 元素的切片语法)

In [24]:
a = np.arange(1, 5, step=1)

print(f"a = {a}")

s = slice(0, 3, 1)
print(f"a[s] = {a[s]}")
print(f"a[0:3] = {a[0:3]}")

a = [1 2 3 4]
a[s] = [1 2 3]
a[0:3] = [1 2 3]
