# 数组集合运算

In [2]:
import numpy as np

from display import aprint
from array_ import arange_by_shape

## 1. 数组的轴

## 1. 舍入函数

## 1. 笛卡尔积

可以对两个数组计算笛卡尔积, 形成两个数组元素的交叉组合

In [4]:
a = np.arange(3, dtype=np.int32)
b = np.arange(100, 500, step=100, dtype=np.int32)

aprint(
    "",
    {
        "a": a,
        "b": b,
        "product(a, b)": np.array(np.meshgrid(a, b)).T.reshape(-1, 2),
    },
)


● a:
[0 1 2], shape=(3,)
● b:
[100 200 300 400], shape=(4,)
● product(a, b):
[[  0 100]
 [  0 200]
 [  0 300]
 [  0 400]
 [  1 100]
 [  1 200]
 [  1 300]
 [  1 400]
 [  2 100]
 [  2 200]
 [  2 300]
 [  2 400]], shape=(12, 2)


In [5]:
import itertools as it

a = np.arange(3, dtype=np.int32)
b = np.arange(100, 500, step=100, dtype=np.int32)

aprint(
    "",
    {
        "a": a,
        "b": b,
        "product(a, b)": np.array([*it.product(a, b)]),
    },
)


● a:
[0 1 2], shape=(3,)
● b:
[100 200 300 400], shape=(4,)
● product(a, b):
[[  0 100]
 [  0 200]
 [  0 300]
 [  0 400]
 [  1 100]
 [  1 200]
 [  1 300]
 [  1 400]
 [  2 100]
 [  2 200]
 [  2 300]
 [  2 400]], shape=(12, 2)


In [6]:
import itertools as it

a = np.arange(3, dtype=np.int32)
b = np.arange(100, 500, step=100, dtype=np.int32)

aprint(
    "",
    {
        "a": a,
        "b": b,
        "product(a, b)": np.array([*it.product(a, b)]),
    },
)


● a:
[0 1 2], shape=(3,)
● b:
[100 200 300 400], shape=(4,)
● product(a, b):
[[  0 100]
 [  0 200]
 [  0 300]
 [  0 400]
 [  1 100]
 [  1 200]
 [  1 300]
 [  1 400]
 [  2 100]
 [  2 200]
 [  2 300]
 [  2 400]], shape=(12, 2)
