# 矩阵

In [1]:
import numpy as np
import colorama as co

from display import aprint

再 Numpy 中, 矩阵 (Matrix) 维度 (dim) 固定为 `2` 的数组 (二维数组)

- 矩阵乘法: `@`
- 矩阵转置: `.T`
- 矩阵转置: `.transpose()`
- 矩阵转置: `.conjugate_transpose()`
- 矩阵转置: `.conjugate()`
- 矩阵转置: `.conj()`
- 矩阵转置: `.H`
- 矩阵转置: `.T`
- 矩阵转置: `.transpose()`

## 1. 创建矩阵

可以将维度小于 `2` ($dim \le 2$) 的数组赋值给矩阵, 得到的矩阵对象维度 (dim) 会自动扩展为 `2`, 即可通过任意维度小于等于 `2` 的数组创建二维矩阵

In [2]:
# 通过单值创建矩阵, 得到的矩阵 shape 为 `(1, 1)`
m1 = np.matrix(10)

# 通过 shape 为 `(1,)` 的一维数组创建矩阵, 得到的矩阵 shape 为 `(1, 1)`
m2 = np.matrix([10])

# 通过 shape 为 `(4,)` 的一维数组创建矩阵, 得到的矩阵 shape 为 `(1, 4)`
m3 = np.matrix([1, 2, 3, 4])

# 通过 shape 为 `(1, 4)` 的二维数组创建矩阵, 得到的矩阵 shape 为 `(1, 4)`
m4 = np.matrix([[1, 2, 3, 4]])

# 通过 shape 为 `(2, 4)` 的二维数组创建矩阵, 得到的矩阵 shape 为 `(2, 4)`
m5 = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])

aprint(
    "矩阵:",
    {
        "m1": m1,
        "m2": m2,
        "m3": m3,
        "m4": m4,
        "m5": m5,
    },
)

矩阵:
● m1:
[[10]], shape=(1, 1)
● m2:
[[10]], shape=(1, 1)
● m3:
[[1 2 3 4]], shape=(1, 4)
● m4:
[[1 2 3 4]], shape=(1, 4)
● m5:
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)


如果通过维度为 2 以上的数组创建矩阵, 则会导致错误

In [3]:
arr = [
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
]

try:
    # 通过三维数组创建矩阵, 会抛出异常
    m6 = np.matrix(arr)
except Exception as e:
    arr = np.array(arr)
    print(
        f"\n{co.Fore.RED}通过数组\n{arr}, dim={arr.ndim}\n创建矩阵失败: {e}{co.Fore.RESET}"
    )


通过数组
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], dim=3
创建矩阵失败: matrix must be 2-dimensional


## 2. 矩阵运算

Numpy 的矩阵运算和二维数组运算规则一致

### 2.1. 矩阵加法

两个矩阵相加, 其运算规则就相当于两个二维数组相加

本例中, 将两个 shape 为 `(2, 2)` 的矩阵进行相加

In [4]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.matrix([[10, 20], [30, 40]])
aprint(
    "两个矩阵相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)

两个矩阵相加
● m1:
[[1 2]
 [3 4]], shape=(2, 2)
● m2:
[[10 20]
 [30 40]], shape=(2, 2)
● m1 + m2:
[[11 22]
 [33 44]], shape=(2, 2)


和二维数组加法类似, 两个矩阵如果 shape 不同, 且不满足广播规则, 则矩阵无法进行加法运算, 会抛出 `ValueError` 错误

In [5]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.matrix([[10, 20, 30], [40, 50, 60]])

try:
    m1 + m2  # type: ignore
except ValueError as e:
    print(
        f"\n{co.Fore.RED}矩阵:\n{m1}, shape={m1.shape}\n和矩阵:\n{m2}, shape={m2.shape}\n无法相加: {e}{co.Fore.RESET}"
    )


矩阵:
[[1 2]
 [3 4]], shape=(2, 2)
和矩阵:
[[10 20 30]
 [40 50 60]], shape=(2, 3)
无法相加: operands could not be broadcast together with shapes (2,2) (2,3) 


可以将矩阵和数组相加, 相加时会将数组转化为矩阵

本例中, 将一个 shape 为 `(2, 2)` 的矩阵和一个 shape 为 `(2, 2)` 的数组进行相加

In [6]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.array([[10, 20], [30, 40]])
aprint(
    "矩阵和二维数组相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)

矩阵和二维数组相加
● m1:
[[1 2]
 [3 4]], shape=(2, 2)
● m2:
[[10 20]
 [30 40]], shape=(2, 2)
● m1 + m2:
[[11 22]
 [33 44]], shape=(2, 2)


如果相加的二维数组不足二维, 则在形成矩阵时会将其转换为二维

本例中, 将一个 shape 为 `(2, 2)` 的矩阵和一个值为 `10` 的标量相加, 整个过程如下:

1. 将标量转换为 shape 为 `(1, 1)` 的矩阵
2. 通过广播机制, 将 shape 为 `(1, 1)` 的矩阵扩展为 shape 为 `(2, 2)` 的矩阵
3. 将两个 shape 为 `(2, 2)` 的矩阵相加

In [7]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.array(10)
aprint(
    "\n矩阵和二维数组相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)


矩阵和二维数组相加
● m1:
[[1 2]
 [3 4]], shape=(2, 2)
● m2:
10, shape=()
● m1 + m2:
[[11 12]
 [13 14]], shape=(2, 2)


如果相加的二维数组不足二维, 则在形成矩阵时会将其转换为二维

本例中, 将一个 shape 为 `(2, 2)` 的矩阵和一个值为 shape 为 `(1,)` 的一维数组相加, 整个过程如下:

1. 将 shape 为 `(1,)` 的一维数组扩展为 shape 为 `(1, 1)` 的矩阵
2. 通过广播机制, 将 shape 为 `(1, 1)` 的矩阵扩展为 shape 为 `(2, 2)` 的矩阵
3. 将两个 shape 为 `(2, 2)` 的矩阵相加

In [8]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.array([10])
aprint(
    "\n矩阵和二维数组相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)


矩阵和二维数组相加
● m1:
[[1 2]
 [3 4]], shape=(2, 2)
● m2:
[10], shape=(1,)
● m1 + m2:
[[11 12]
 [13 14]], shape=(2, 2)


如果相加的二维数组不足二维, 则在形成矩阵时会将其转换为二维

本例中, 将一个 shape 为 `(2, 2)` 的矩阵和一个 shape 为 `(2,)` 的数组相加, 整个过程如下:

1. 将 shape 为 `(2,)` 的数组扩展为 shape 为 `(1, 2)` 的矩阵
2. 通过广播机制, 将 shape 为 `(1, 2)` 的矩阵扩展为 shape 为 `(2, 2)` 的矩阵
3. 将两个 shape 为 `(2, 2)` 的矩阵相加

In [9]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.array([10, 20])
aprint(
    "\n矩阵和二维数组相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)


矩阵和二维数组相加
● m1:
[[1 2]
 [3 4]], shape=(2, 2)
● m2:
[10 20], shape=(2,)
● m1 + m2:
[[11 22]
 [13 24]], shape=(2, 2)
