# 数组运算

Numpy 数组支持多种运算, 包括加减乘除等, 而且语法非常直观简便

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]])
b = np.array([[10, 20, 30, 40], [20, 30, 40, 50], [30, 40, 50, 60]])
print(a + b)

[[11 22 33 44]
 [22 33 44 55]
 [33 44 55 66]]


## 1. 加法运算

两个形状相同的数组可以进行加法运算, 例如:

$
\begin{bmatrix}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 5 \\
3 & 4 & 5 & 6 \\
\end{bmatrix}+
\begin{bmatrix}
10 & 20 & 30 & 40 \\
20 & 30 & 40 & 50 \\
30 & 40 & 50 & 60 \\
\end{bmatrix}=
\begin{bmatrix}
11 & 22 & 33 & 44 \\
22 & 33 & 44 & 55 \\
33 & 44 & 55 & 66 \\
\end{bmatrix}
$

从上面矩阵加法结果可扩展, 两个形状相同的数组相加, 即将两个数组位置相同的元素相加, 并在结果数组相同位置存放结果元素

In [3]:
# 将两个长度相同的一维数组相加
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
ans = a + b
print(
    f"一维数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

# 将两个形状相同的二维数组相加
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
ans = a + b
print(
    f"\n二维数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

# 将两个形状相同的三维数组相加
a = np.arange(1, 25).reshape(2, 3, 4)
b = np.arange(10, 34).reshape(2, 3, 4)
ans = a + b
print(
    f"\n三维数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

一维数组相加:
a:
[1 2 3 4], shape=(4,)
b:
[5 6 7 8], shape=(4,)
a + b:
[ 6  8 10 12], shape=(4,)

二维数组相加:
a:
[[1 2]
 [3 4]], shape=(2, 2)
b:
[[5 6]
 [7 8]], shape=(2, 2)
a + b:
[[ 6  8]
 [10 12]], shape=(2, 2)

三维数组相加:
a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
b:
[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]
  [30 31 32 33]]], shape=(2, 3, 4)
a + b:
[[[11 13 15 17]
  [19 21 23 25]
  [27 29 31 33]]

 [[35 37 39 41]
  [43 45 47 49]
  [51 53 55 57]]], shape=(2, 3, 4)


如果两个数组具备相同维度, 但形状不同 (例如两个一维数组, 但长度不同), 则这两个数组无法进行加法运算

如果两个数组维度不同, 但每个维度具备相同数量的元素, 则两个数组可以借助 Numpy 的广播机制进行相加

In [4]:
# 测试长度不同的两个一维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([1, 2, 3])
    b = np.array([5, 6, 7, 8])
    ans = a + b
except ValueError as e:
    print(f"一维数组相加失败: {e}")

# 测试两个列长度不同的二维数组相加, 会抛出 `ValueError` 异常
try:
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6], [7, 8, 9]])
    ans = a + b
except ValueError as e:
    print(f"二维数组相加失败: {e}")

一维数组相加失败: operands could not be broadcast together with shapes (3,) (4,) 
二维数组相加失败: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.


## 2. 乘法运算

## 3. 广播机制

Numpy 提供了广播 (broadcast) 机制, 用于对不同形状的数组进行数学操作的功能, 对于 `x` 和 `y` 两个矩阵:

$
x =
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
$

$
y =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
\end{bmatrix}
$

则

$
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
\centerdot
\begin{bmatrix}
1 & 2 & 3 & 4 \\
\end{bmatrix}
\rightarrow
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
\centerdot
\begin{bmatrix}
1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 \\
\end{bmatrix}
$

可以看到, 两个矩阵如果维度不同 (即矩阵的列数量不同), 但现有列的元素数一致, 则运算时, 会将列较少的矩阵进行扩展, 使其和另一个矩阵的列数一致, 扩展的方法为: 将矩阵的最后一列进行复制, 复制两个矩阵列相差数量次

推广到多维数组, 则数组广播的规则为:

- 如果两个数组的维数 (dim) 不同, 则形状 (shape) 数量较少的数组会在形状前前面补 `1` (例如最大维度为 `3`, 则如果有数组的 shape 为 `(2, 3)`, 则自动扩展为 `(1, 2, 3)`)
- 如果两个数组的形状在某个维度上不匹配, 且其中一个维度长度为 `1`, 则会沿该维度复制扩展以匹配另一个数组的形状
- 如果在任何维度上都不匹配且没有维度等于 `1`，则会引发异常

### 3.1. 通过广播扩展维度

对于两个数组 `a` 与 `b`:

- 数组 `a` 的 shape 为 `(1, 4)`
- 数组 `b` 的 shape 为 `(2, 4)`

故 `a`, `b` 两个数组的维度相同, 且 `a` 数组的 shape 第一项为 `1`, 则通过广播机制, 将 `a` 数组沿 shape 为 `1` 的轴进行复制, 使其 shape 变为 `(2, 4)`

广播后, `a` + `b` 结果如下:

$
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix} &
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}
\end{bmatrix} +
\begin{bmatrix}
\begin{bmatrix}
5 & 6 & 7 & 8
\end{bmatrix} &
\begin{bmatrix}
9 & 10 & 11 & 12
\end{bmatrix}
\end{bmatrix}=
\begin{bmatrix}
\begin{bmatrix}
6 & 8 & 10 & 12
\end{bmatrix} &
\begin{bmatrix}
10 & 12 & 14 & 16
\end{bmatrix}
\end{bmatrix}
$

In [5]:
# 数组 `a` 的 shape 为 `(1, 4)` (二维数组), 数组 `b` 的 shape 为 `(2, 4)` (二维数组), 两个数组维度相同
# 1. 将数组 `a` 沿 shape 为 `1` 的维度进行复制, 使其 shape 为 `(2, 4)`, 即 `a` 变为 `[[1, 2, 3, 4], [1, 2, 3, 4]]`
# 3. 此时 `a`, `b` 数组的 shape 相同, 可以将 `a` 和 `b` 相加
a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(
    f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

数组相加:
a:
[[1 2 3 4]], shape=(1, 4)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[ 6  8 10 12]
 [10 12 14 16]], shape=(2, 4)


对于两个数组 `a` 与 `b`:

- 数组 `a` 的 shape 为 `(4,)`
- 数组 `b` 的 shape 为 `(2, 4)`

故 `a`, `b` 两个数组的维度不同, 且 `a` 数组 shape 的后几位和 `b` 数组相同, 则通过广播机制, 在 `a` 数组的 shape 第一位补 `1`, 使其 shape 变为 `(1, 4)`, 在沿 shape 为 `1` 的维度进行复制, 是其 shape 变为 `(2, 4)`

广播后, `a` + `b` 结果如下:

$
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix} &
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}
\end{bmatrix} +
\begin{bmatrix}
\begin{bmatrix}
5 & 6 & 7 & 8
\end{bmatrix} &
\begin{bmatrix}
9 & 10 & 11 & 12
\end{bmatrix}
\end{bmatrix}=
\begin{bmatrix}
\begin{bmatrix}
6 & 8 & 10 & 12
\end{bmatrix} &
\begin{bmatrix}
10 & 12 & 14 & 16
\end{bmatrix}
\end{bmatrix}
$

In [6]:
# 数组 `a` 的 shape 为 `(4,)` (一维数组), 数组 `b` 的 shape 为 `(2, 4)` (二维数组), 两个数组维度不同
# 1. 在数组 `a` 的 shape 前面补 `1`, 使其 shape 变为 `(1, 4)`, 使其变为 `[[1, 2, 3, 4]]`
# 2. 将数组 `a` 沿 shape 为 `1` 的维度进行复制, 使其 shape 为 `(2, 4)`, 即 `a` 变为 `[[1, 2, 3, 4], [1, 2, 3, 4]]`
# 3. 此时 `a`, `b` 数组的 shape 相同, 可以将 `a` 和 `b` 相加
a = np.array([1, 2, 3, 4])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(
    f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

数组相加:
a:
[1 2 3 4], shape=(4,)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[ 6  8 10 12]
 [10 12 14 16]], shape=(2, 4)


对于两个数组 `a` 与 `b`:

- 数组 `a` 的 shape 为 `(2, 1)`
- 数组 `b` 的 shape 为 `(2, 4)`

故 `a`, `b` 两个数组的维度相同, 且两个数组的 shape 第一项相同, 则将 `a` 数组沿 shape 为 `1` 的维度进行复制, 是其 shape 变为 `(2, 4)`

广播后, `a` + `b` 结果如下:

$
\begin{bmatrix}
\begin{bmatrix}
10 & 10 & 10 & 10
\end{bmatrix} &
\begin{bmatrix}
11 & 11 & 11 & 11
\end{bmatrix}
\end{bmatrix} +
\begin{bmatrix}
\begin{bmatrix}
5 & 6 & 7 & 8
\end{bmatrix} &
\begin{bmatrix}
9 & 10 & 11 & 12
\end{bmatrix}
\end{bmatrix}=
\begin{bmatrix}
\begin{bmatrix}
15 & 16 & 17 & 18
\end{bmatrix} &
\begin{bmatrix}
20 & 21 & 22 & 23
\end{bmatrix}
\end{bmatrix}
$

In [7]:
# 数组 `a` 的 shape 为 `(2, 1)` (二维数组), 数组 `b` 的 shape 为 `(2, 4)` (二维数组), 两个数组维度相同
# 1. 将数组 `a` 沿 shape 为 `1` 的维度进行复制, 使其 shape 为 `(2, 4)`, 即 `a` 变为 `[[10, 10, 10, 10], [11, 11, 11, 11]]`
# 2. 此时 `a`, `b` 数组的 shape 相同, 可以将 `a` 和 `b` 相加
a = np.array([[10], [11]])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(
    f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

数组相加:
a:
[[10]
 [11]], shape=(2, 1)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[15 16 17 18]
 [20 21 22 23]], shape=(2, 4)


对于两个数组 `a` 与 `b`:

- 数组 `a` 的 shape 为 `(1, 1)`
- 数组 `b` 的 shape 为 `(2, 4)`

故 `a`, `b` 两个数组的维度相同, 且 `a` 数组的 shape 均为 `1`, 故将 `a` 数组沿两个 shape 为 `1` 的维度进行复制, 使其 shape 变为 `(2, 4)`

广播后, `a` + `b` 结果如下:

$
\begin{bmatrix}
\begin{bmatrix}
10 & 10 & 10 & 10
\end{bmatrix} &
\begin{bmatrix}
10 & 10 & 10 & 10
\end{bmatrix}
\end{bmatrix} +
\begin{bmatrix}
\begin{bmatrix}
5 & 6 & 7 & 8
\end{bmatrix} &
\begin{bmatrix}
9 & 10 & 11 & 12
\end{bmatrix}
\end{bmatrix}=
\begin{bmatrix}
\begin{bmatrix}
15 & 16 & 17 & 18
\end{bmatrix} &
\begin{bmatrix}
19 & 20 & 21 & 22
\end{bmatrix}
\end{bmatrix}
$

In [8]:
# 数组 `a` 的 shape 为 `(1, 1)` (二维数组), 数组 `b` 的 shape 为 `(2, 4)` (二维数组), 两个数组维度相同
# 1. 将数组 `a` 沿 shape 为 `1` 的维度进行复制 (两个维度), 使其 shape 为 `(2, 4)`, 即 `a` 变为 `[[10, 10, 10, 10], [10, 10, 10, 10]]`
# 2. 此时 `a`, `b` 数组的 shape 相同, 可以将 `a` 和 `b` 相加
a = np.array([[10]])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(
    f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

数组相加:
a:
[[10]], shape=(1, 1)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[15 16 17 18]
 [19 20 21 22]], shape=(2, 4)


In [11]:
# 数组 `a` 的 shape 为 `(2, 1)` (二维数组), 数组 `b` 的 shape 为 `(2, 4)` (二维数组), 两个数组维度相同
# 1. 将数组 `a` 沿 shape 为 `1` 的维度进行复制, 使其 shape 为 `(2, 4)`, 即 `a` 变为 `[[10, 10, 10, 10], [11, 11, 11, 11]]`
# 2. 此时 `a`, `b` 数组的 shape 相同, 可以将 `a` 和 `b` 相加
a = np.array([10])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(
    f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}"
)

数组相加:
a:
[10], shape=(1,)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[15 16 17 18]
 [19 20 21 22]], shape=(2, 4)
