# 数组

首先, 导入 Numpy 模块

In [1]:
import numpy as np

## 1. 创建数组

### 1.1. 通过 Python 数组创建

In [2]:
# 通过一维 Python 数组创建 NumPy 数组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}")

# 通过二维 Python 数组创建 NumPy 数组
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\n二维数组内容:\n{data}")

# 通过三维 Python 列表创建 NumPy 数组
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1 2 3 4]

二维数组内容:
[[1 2 3 4]
 [5 6 7 8]]

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 1.2. 创建元素值为 `0` 的数组

In [3]:
# 创建元素值为 0 的一维数组
data = np.zeros(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 0 的二维数组
data = np.zeros(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 0 的三维数组
data = np.zeros(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[0. 0. 0. 0.]

二维数组内容:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

三维数组内容:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
# 创建元素值为 1 的一维数组
data = np.ones(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 1 的二维数组
data = np.ones(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 1 的三维数组
data = np.ones(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.3. 创建元素值为 "空" 的数组

通过 `np.empty` 函数创建一个元素值为 "空" 的数组

注意: 所谓元素值为 "空" 的数组，指的是直接分配内存, 且不会对元素所用内存进行初始化操作, 所以所分配内存中的内容是未知的 (或保留上次该区域内存使用的值)

所以创建了元素值为 "空" 的数组后, 必须对数组元素值全部进行初始化

对于已确定会对数组元素值进行全部初始化的场景, 通过 `np.empty` 函数创建数组可以提升程序效率

In [5]:
# 创建元素值未知的一维数组
data = np.empty(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值未知的二维数组
data = np.empty(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值未知的三维数组
data = np.empty(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.4. 创建元素值为连续序列的数组

In [6]:
data = np.linspace(1, 10, 10)
print(f"数组内容:\n{data}")

data = np.linspace(1, 10, 20)
print(f"\n数组内容:\n{data}")

数组内容:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

数组内容:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 1.5. 创建元素值为 `0`~`1` 随机数的数组

In [7]:
# 创建随机元素值的一维数组
data = np.random.rand(4)
print(f"数组内容:\n{data}")

# 创建随机元素值的二维数组
data = np.random.rand(3, 4)
print(f"\n数组内容:\n{data}")

# 创建随机元素值的三维数组
data = np.random.rand(2, 3, 4)
print(f"\n数组内容:\n{data}")

# `np.random.rand` 函数不能指定随机数范围, 只能生成 `0`~`1` 之间的随机数
# 要指定随机数范围, 可通过下面的计算方法
min_, max_ = 5, 10
data = min_ + (max_ - min_) * (np.random.rand(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[0.13372918 0.0333479  0.68682028 0.78956463]

数组内容:
[[0.16949048 0.82262581 0.80469329 0.01912993]
 [0.42766165 0.83809147 0.88422894 0.78243979]
 [0.83036305 0.14859263 0.26632878 0.63541189]]

数组内容:
[[[0.86991244 0.64434902 0.209294   0.77568096]
  [0.60712314 0.88237521 0.09368404 0.03368671]
  [0.02866205 0.81287889 0.24540999 0.93166323]]

 [[0.55047956 0.8516917  0.79028579 0.0827746 ]
  [0.29383887 0.68024547 0.45547144 0.40505497]
  [0.97598042 0.44167063 0.74411024 0.0535626 ]]]

数组内容:
[[[7.12864908 6.73791061 8.76744893 6.22463771]
  [8.55699272 8.40524392 9.05901546 7.96995795]
  [7.48502433 5.96945071 5.78900038 7.76223378]]

 [[7.00208931 7.52060889 6.82323247 7.32239212]
  [5.93037287 7.36701833 7.33396155 5.78689857]
  [7.78125255 6.99437816 8.15388041 9.91884721]]]


### 1.6. 创建元素值随机整数的数组

In [8]:
# 创建元素值为 `1`~`10` 之间随机数的一维数组
data = np.random.randint(1, 10, size=(4,))
print(f"数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的二维数组
data = np.random.randint(1, 10, size=(3, 4))
print(f"\n数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的三维数组
data = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[1 9 6 5]

数组内容:
[[5 2 2 5]
 [8 5 9 9]
 [2 8 6 9]]

数组内容:
[[[6 3 5 1]
  [6 3 3 8]
  [9 9 9 9]]

 [[2 7 3 3]
  [6 3 5 8]
  [5 3 1 4]]]


## 2. 数组形状

### 2.1. 获取数组形状

In [9]:
# 获取一维数组的形状, 结果为一个包含一个值的元组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}, 形状: {data.shape}")

# 获取二维数组的形状, 结果为一个包含两个值的元组, 表示数组的两个维度
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组内容:\n{data}, 形状: {data.shape}")

# 获取三维数组的形状, 结果为一个包含三个值的元组, 描述数组的三个维度
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}, 形状: {data.shape}")

一维数组内容:
[1 2 3 4], 形状: (4,)

二维数组内容:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], 形状: (3, 4)

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)


### 2.2. 改变数组的形状

In [10]:
# 定义一个 24 个元素的一维数组
data = np.arange(1, 25)
print(f"数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将一维数组改为二维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, -1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将二维数组改为三维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, 3, -1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将三维数组改为一维数组
data = data.reshape(-1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 如果目标形状无法达成 (及元素个数无法满足目标形状要求), 则操作失败
# data = data.reshape(2, 5, -1)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], 形状: (24,)

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], 形状: (2, 12)

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], 形状: (24,)


## 3. 数组转置

转置是线性代数的一个概念, 及将 $m \times n$ 矩阵转置为 $n \times m$ 矩阵, 矩阵中元素的位置关系不变, 例如:

对于矩阵
$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$, 其转置矩阵为
$
A^T=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}
$

Numpy 支持多维数组 (多维矩阵), 故可对多维数组进行转置, 例如对于三维数组, 可将 $m \times n \times k$ 矩阵转置为 $k \times n \times m$

In [11]:
data = np.arange(1, 25).reshape(2, 3, 4)
print(f"数组内容:\n{data}, 形状: {data.shape}")

data = data.T
print(f"\n转置后数组内容:\n{data}, 形状: {data.shape}")

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)

转置后数组内容:
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], 形状: (4, 3, 2)
