# 数组运算

In [1]:
import numpy as np

## 1. 加法运算

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
ans = a + b
print(f"一维数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}")

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
ans = a + b
print(f"\n二维数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}")

一维数组相加:
a:
[1 2 3 4], shape=(4,)
b:
[5 6 7 8], shape=(4,)
a + b:
[ 6  8 10 12], shape=(4,)

二维数组相加:
a:
[[1 2]
 [3 4]], shape=(2, 2)
b:
[[5 6]
 [7 8]], shape=(2, 2)
a + b:
[[ 6  8]
 [10 12]], shape=(2, 2)


In [3]:
try:
    a = np.array([1, 2, 3])
    b = np.array([5, 6, 7, 8])
    ans = a + b
except ValueError as e:
    print(f"一维数组相加失败: {e}")

try:
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6], [7, 8, 9]])
    ans = a + b
except ValueError as e:
    print(f"二维数组相加失败: {e}")

一维数组相加失败: operands could not be broadcast together with shapes (3,) (4,) 
二维数组相加失败: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.


## 2. 乘法运算

## 3. 广播机制

Numpy 提供了广播 (broadcast) 机制, 用于对不同形状的数组进行数学操作的功能, 对于 `x` 和 `y` 两个矩阵:

$
x =
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
$

$
y =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
\end{bmatrix}
$

则

$
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
\centerdot
\begin{bmatrix}
1 & 2 & 3 & 4 \\
\end{bmatrix}
\rightarrow
\begin{bmatrix}
-0.0 & -0.1 & -0.2 & -0.3 \\
-0.4 & -0.5 & -0.6 & -0.7 \\
-0.8 & -0.9 & -1.0 & -1.1 \\
\end{bmatrix}
\centerdot
\begin{bmatrix}
1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 \\
\end{bmatrix}
$


广播规则:

- 让所有输入数组都向其中形状最长的数组看齐, 形状中不足的部分都通过在前面加 `1` 补齐
- 输出数组的形状是输入数组形状的各个维度上的最大值
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 `1` 时, 这个数组能够用来计算, 否则出错
- 当输入数组的某个维度的长度为 `1` 时, 沿着此维度运算时都用此维度上的第一组值

简单理解: 对两个数组, 分别比较他们的每一个维度 (若其中一个数组没有当前维度则忽略), 满足:

- 数组拥有相同形状
- 当前维度的值相等
- 当前维度的值有一个是 `1`
- 若条件不满足, 抛出 "ValueError: frames are not aligned" 异常

In [7]:
a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])
ans = a + b
print(f"数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}")

a = np.array(np.arange(1, 25).reshape(2, 3, 4))
b = np.array(np.arange(25, 25 + 36).reshape(3, 3, 4))
ans = a + b
print(f"\n数组相加:\na:\n{a}, shape={a.shape}\nb:\n{b}, shape={b.shape}\na + b:\n{ans}, shape={ans.shape}")

数组相加:
a:
[[1 2 3 4]], shape=(1, 4)
b:
[[ 5  6  7  8]
 [ 9 10 11 12]], shape=(2, 4)
a + b:
[[ 6  8 10 12]
 [10 12 14 16]], shape=(2, 4)


ValueError: operands could not be broadcast together with shapes (2,3,4) (3,3,4) 