# 数组属性

In [1]:
import numpy as np

数组的属性包括:

- `shape`: 数组形状, 即数组的维数和每个维度的长度
- `ndim`: 数组维数, 包括: `1` 为一维数组 (标量), `2` 为二维数组 (矢量), `3` 为三维数组等 (矩阵), `4` 为四维数组 (张量) 等
- `size`: 数组元素个数
- `dtype`: 数组元素数据类型

In [2]:
data = np.arange(1, 25)  # 创建一个包含 1 到 24 的一维数组
print(f"数组内容:\n{data}\nDim: {data.ndim}\nShape: {data.shape}\nSize: {data.size}\nDtype: {data.dtype}")

data = data.reshape(2, -1)
print(f"\n数组内容:\n{data}\nDim: {data.ndim}\nShape: {data.shape}\nSize: {data.size}\nDtype: {data.dtype}")

data = data.reshape(2, 3, -1)
print(f"\n数组内容:\n{data}\nDim: {data.ndim}\nShape: {data.shape}\nSize: {data.size}\nDtype: {data.dtype}")

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Dim: 1
Shape: (24,)
Size: 24
Dtype: int64

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
Dim: 2
Shape: (2, 12)
Size: 24
Dtype: int64

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dim: 3
Shape: (2, 3, 4)
Size: 24
Dtype: int64
