# 数组

首先, 导入 Numpy 模块

In [16]:
import numpy as np

## 1. 创建数组

### 1.1. 通过 Python 数组创建

In [17]:
# 通过一维 Python 数组创建 NumPy 数组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}")

# 通过二维 Python 数组创建 NumPy 数组
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\n二维数组内容:\n{data}")

# 通过三维 Python 列表创建 NumPy 数组
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1 2 3 4]

二维数组内容:
[[1 2 3 4]
 [5 6 7 8]]

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 1.2. 创建元素值为 `0` 的数组

In [18]:
# 创建元素值为 0 的一维数组
data = np.zeros(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 0 的二维数组
data = np.zeros(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 0 的三维数组
data = np.zeros(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[0. 0. 0. 0.]

二维数组内容:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

三维数组内容:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [19]:
# 创建元素值为 1 的一维数组
data = np.ones(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 1 的二维数组
data = np.ones(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 1 的三维数组
data = np.ones(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.3. 创建元素值为 "空" 的数组

通过 `np.empty` 函数创建一个元素值为 "空" 的数组

注意: 所谓元素值为 "空" 的数组，指的是直接分配内存, 且不会对元素所用内存进行初始化操作, 所以所分配内存中的内容是未知的 (或保留上次该区域内存使用的值)

所以创建了元素值为 "空" 的数组后, 必须对数组元素值全部进行初始化

对于已确定会对数组元素值进行全部初始化的场景, 通过 `np.empty` 函数创建数组可以提升程序效率

In [20]:
# 创建元素值未知的一维数组
data = np.empty(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值未知的二维数组
data = np.empty(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值未知的三维数组
data = np.empty(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.4. 创建元素值为连续序列的数组

In [21]:
data = np.linspace(1, 10, 10)
print(f"数组内容:\n{data}")

data = np.linspace(1, 10, 20)
print(f"\n数组内容:\n{data}")

数组内容:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

数组内容:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 1.5. 创建元素值为 `0`~`1` 随机数的数组

In [22]:
# 创建随机元素值的一维数组
data = np.random.rand(4)
print(f"数组内容:\n{data}")

# 创建随机元素值的二维数组
data = np.random.rand(3, 4)
print(f"\n数组内容:\n{data}")

# 创建随机元素值的三维数组
data = np.random.rand(2, 3, 4)
print(f"\n数组内容:\n{data}")

# `np.random.rand` 函数不能指定随机数范围, 只能生成 `0`~`1` 之间的随机数
# 要指定随机数范围, 可通过下面的计算方法
min_, max_ = 5, 10
data = min_ + (max_ - min_) * (np.random.rand(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[0.72473162 0.40229285 0.87301401 0.79311857]

数组内容:
[[0.24805985 0.19076982 0.27056334 0.99000223]
 [0.27085963 0.65713882 0.93406098 0.94605225]
 [0.86825613 0.94097939 0.93625178 0.61904428]]

数组内容:
[[[0.81694615 0.95443551 0.15093169 0.36933353]
  [0.09219509 0.06365912 0.70777513 0.60786841]
  [0.52245033 0.18993293 0.58185064 0.07007947]]

 [[0.60418434 0.37675169 0.63858416 0.09047789]
  [0.66965261 0.15697299 0.57621243 0.85198253]
  [0.92808027 0.60891901 0.44368008 0.55435026]]]

数组内容:
[[[9.94328211 8.47131175 5.22094114 8.55183672]
  [8.45789347 8.9709093  7.74641538 6.22719917]
  [9.83898456 9.21645312 6.79035454 7.36557016]]

 [[8.86107894 6.09694668 8.51613507 9.27049268]
  [9.16829908 6.66619731 5.11337191 5.04758939]
  [9.36956193 8.29545533 9.95659582 6.1541396 ]]]


### 1.6. 创建元素值随机整数的数组

In [23]:
# 创建元素值为 `1`~`10` 之间随机数的一维数组
data = np.random.randint(1, 10, size=(4,))
print(f"数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的二维数组
data = np.random.randint(1, 10, size=(3, 4))
print(f"\n数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的三维数组
data = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[6 1 6 2]

数组内容:
[[1 6 9 2]
 [8 2 9 1]
 [1 9 3 3]]

数组内容:
[[[7 4 5 7]
  [5 6 8 7]
  [2 8 7 4]]

 [[1 7 1 4]
  [6 8 8 3]
  [7 5 6 9]]]


## 2. 数组属性

### 2.1. 数组维度 (`ndim`)

可以获取到一个数组包含的维度数

In [30]:
# 一维数组的 dim 总为 `1`
data = np.arange(1, 25)  # 创建一个包含 1 到 24 的一维数组
print(f"一维数组:\n{data}, dim={data.ndim}")

# 二维数组的 dim 总为 `2`
data = data.reshape(2, -1)
print(f"\n二维数组:\n{data}, dim={data.ndim}")

# 三维数组的 dim 总为 `3`
data = data.reshape(2, 3, -1)
print(f"\n三维数组:\n{data}, dim={data.ndim}")

一维数组:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], dim=1

二维数组:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], dim=2

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], dim=3


### 2.2. 数组形状 (`shape`)

数组的形状即数组在每个维度的长度, 例如 shape 为 `(2, 3)` 的数组, 表示一个有 `2` 行 `3` 列的二维数组

In [31]:
# 获取一维数组的形状, 结果为一个包含一个值的元组
data = np.array([1, 2, 3, 4])
print(f"一维数组:\n{data}, shape={data.shape}")

# 获取二维数组的形状, 结果为一个包含两个值的元组, 表示数组的两个维度
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组:\n{data}, shape={data.shape}")

# 获取三维数组的形状, 结果为一个包含三个值的元组, 描述数组的三个维度
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组:\n{data}, shape={data.shape}")

一维数组:
[1 2 3 4], shape=(4,)

二维数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4)

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)


### 2.3. 数组长度 (`size`)

数组长度即数组包含的元素总数, 和数组的维度或数组的形状无关

In [32]:
data = np.array([1, 2, 3, 4])
print(f"一维数组:\n{data}, size={data.size}")

data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组:\n{data}, size={data.size}")

data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组:\n{data}, size={data.size}")

一维数组:
[1 2 3 4], size=4

二维数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], size=12

三维数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], size=24


### 2.4. 数组元素类型 (`dtype`)

数组中的元素具备统一的数据类型, 可通过 `np.dtype` 查看, 可能的类型包括:

- `np.int8`: 8 位有符号整数
- `np.int16`: 16 位有符号整数
- `np.int32`: 32 位有符号整数
- `np.int64`: 64 位有符号整数
- `np.uint8`: 8 位无符号整数
- `np.uint16`: 16 位无符号整数
- `np.uint32`: 32 位无符号整数
- `np.uint64`: 64 位无符号整数
- `np.float16`: 16 位浮点数
- `np.float32`: 32 位浮点数
- `np.float64`: 64 位浮点数
- `np.complex64`: 64 位复数
- `np.complex128`: 128 位复数
- `np.bool_`: 布尔值

In [33]:
data = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(f"数组:\n{data}, dtype={data.dtype}")

data = data * np.array([0.01])
print(f"\n数组:\n{data}, dtype={data.dtype}")

data = np.array([n >= 0.1 for n in data.flat]).reshape(data.shape)
print(f"\n数组:\n{data}, dtype={data.dtype}")

数组:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], dtype=int64

数组:
[[[0.01 0.02 0.03 0.04]
  [0.05 0.06 0.07 0.08]
  [0.09 0.1  0.11 0.12]]], dtype=float64

数组:
[[[False False False False]
  [False False False False]
  [False  True  True  True]]], dtype=bool


## 3. 改变数组的形状

In [34]:
# 定义一个 24 个元素的一维数组
data = np.arange(1, 25)
print(f"数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将一维数组改为二维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, -1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将二维数组改为三维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, 3, -1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 改变数组的形状, 将三维数组改为一维数组
data = data.reshape(-1)
print(f"\n数组内容:\n{data}, shape={data.shape}")

# 如果目标形状无法达成 (及元素个数无法满足目标形状要求), 则操作失败
# data = data.reshape(2, 5, -1)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12)

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,)


## 4. 数组转置

转置是线性代数的一个概念, 及将 $m \times n$ 矩阵转置为 $n \times m$ 矩阵, 矩阵中元素的位置关系不变, 例如:

对于矩阵
$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$, 其转置矩阵为
$
A^T=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}
$

Numpy 支持多维数组 (多维矩阵), 故可对多维数组进行转置, 例如对于三维数组, 可将 $m \times n \times k$ 矩阵转置为 $k \times n \times m$

In [35]:
data = np.arange(1, 25).reshape(2, 3, 4)
print(f"数组内容:\n{data}, shape={data.shape}")

data = data.T
print(f"\n转置后数组内容:\n{data}, shape={data.shape}")

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)

转置后数组内容:
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], shape=(4, 3, 2)
