# 数组

首先, 导入 Numpy 模块

In [15]:
import numpy as np

## 1. 创建数组

### 1.1. 通过 Python 数组创建

In [16]:
# 通过一维 Python 数组创建 NumPy 数组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}")

# 通过二维 Python 数组创建 NumPy 数组
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"\n二维数组内容:\n{data}")

# 通过三维 Python 列表创建 NumPy 数组
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1 2 3 4]

二维数组内容:
[[1 2 3 4]
 [5 6 7 8]]

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 1.2. 创建元素值为 `0` 的数组

In [17]:
# 创建元素值为 0 的一维数组
data = np.zeros(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 0 的二维数组
data = np.zeros(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 0 的三维数组
data = np.zeros(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[0. 0. 0. 0.]

二维数组内容:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

三维数组内容:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
# 创建元素值为 1 的一维数组
data = np.ones(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值为 1 的二维数组
data = np.ones(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值为 1 的三维数组
data = np.ones(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.3. 创建元素值为 "空" 的数组

通过 `np.empty` 函数创建一个元素值为 "空" 的数组

注意: 所谓元素值为 "空" 的数组，指的是直接分配内存, 且不会对元素所用内存进行初始化操作, 所以所分配内存中的内容是未知的 (或保留上次该区域内存使用的值)

所以创建了元素值为 "空" 的数组后, 必须对数组元素值全部进行初始化

对于已确定会对数组元素值进行全部初始化的场景, 通过 `np.empty` 函数创建数组可以提升程序效率

In [19]:
# 创建元素值未知的一维数组
data = np.empty(shape=(4))
print(f"一维数组内容:\n{data}")

# 创建元素值未知的二维数组
data = np.empty(shape=(3, 4))
print(f"\n二维数组内容:\n{data}")

# 创建元素值未知的三维数组
data = np.empty(shape=(2, 3, 4))
print(f"\n三维数组内容:\n{data}")

一维数组内容:
[1. 1. 1. 1.]

二维数组内容:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

三维数组内容:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 1.4. 创建元素值为连续序列的数组

In [20]:
data = np.linspace(1, 10, 10)
print(f"数组内容:\n{data}")

data = np.linspace(1, 10, 20)
print(f"\n数组内容:\n{data}")

数组内容:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

数组内容:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 1.5. 创建元素值为 `0`~`1` 随机数的数组

In [21]:
# 创建随机元素值的一维数组
data = np.random.rand(4)
print(f"数组内容:\n{data}")

# 创建随机元素值的二维数组
data = np.random.rand(3, 4)
print(f"\n数组内容:\n{data}")

# 创建随机元素值的三维数组
data = np.random.rand(2, 3, 4)
print(f"\n数组内容:\n{data}")

# `np.random.rand` 函数不能指定随机数范围, 只能生成 `0`~`1` 之间的随机数
# 要指定随机数范围, 可通过下面的计算方法
min_, max_ = 5, 10
data = min_ + (max_ - min_) * (np.random.rand(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[0.44651041 0.9220085  0.66889919 0.18974711]

数组内容:
[[0.94153804 0.6699549  0.44415161 0.48147601]
 [0.18911489 0.21889774 0.21258752 0.46440778]
 [0.9369614  0.72729804 0.25496466 0.44773727]]

数组内容:
[[[0.93863224 0.81271091 0.84817964 0.74082869]
  [0.40473736 0.34619832 0.16713956 0.08808747]
  [0.09827499 0.23707418 0.36786532 0.44645806]]

 [[0.10931409 0.86887171 0.31546308 0.08410474]
  [0.58143217 0.85823201 0.68074382 0.58662239]
  [0.23096579 0.66442069 0.2093175  0.68710502]]]

数组内容:
[[[6.83007461 9.44330796 7.84188687 6.65843275]
  [8.2947048  7.98462457 7.27231368 8.75524656]
  [6.52557522 8.68558126 8.74615494 6.12902457]]

 [[9.71956811 5.35881941 8.93651295 8.35977376]
  [6.76048381 5.55338069 7.86855589 5.55188247]
  [7.34644778 7.60147822 5.39781183 6.0777355 ]]]


### 1.6. 创建元素值随机整数的数组

In [22]:
# 创建元素值为 `1`~`10` 之间随机数的一维数组
data = np.random.randint(1, 10, size=(4,))
print(f"数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的二维数组
data = np.random.randint(1, 10, size=(3, 4))
print(f"\n数组内容:\n{data}")

# 创建元素值为 `1`~`10` 之间随机数的三维数组
data = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n数组内容:\n{data}")

数组内容:
[4 4 8 8]

数组内容:
[[9 2 3 1]
 [8 3 8 9]
 [5 1 3 9]]

数组内容:
[[[2 6 4 7]
  [5 8 1 6]
  [4 9 9 6]]

 [[4 4 8 6]
  [8 9 9 6]
  [5 6 7 1]]]


## 2. 数组形状

### 2.1. 获取数组形状

In [23]:
# 获取一维数组的形状, 结果为一个包含一个值的元组
data = np.array([1, 2, 3, 4])
print(f"一维数组内容:\n{data}, 形状: {data.shape}")

# 获取二维数组的形状, 结果为一个包含两个值的元组, 表示数组的两个维度
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n二维数组内容:\n{data}, 形状: {data.shape}")

# 获取三维数组的形状, 结果为一个包含三个值的元组, 描述数组的三个维度
data = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(f"\n三维数组内容:\n{data}, 形状: {data.shape}")

一维数组内容:
[1 2 3 4], 形状: (4,)

二维数组内容:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], 形状: (3, 4)

三维数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)


### 2.2. 改变数组的形状

In [24]:
# 定义一个 24 个元素的一维数组
data = np.arange(1, 25)
print(f"数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将一维数组改为二维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, -1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将二维数组改为三维数组
# `-1` 表示自动计算维度, 只有最后一个维度可以为 `-1`
data = data.reshape(2, 3, -1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 改变数组的形状, 将三维数组改为一维数组
data = data.reshape(-1)
print(f"\n数组内容:\n{data}, 形状: {data.shape}")

# 如果目标形状无法达成 (及元素个数无法满足目标形状要求), 则操作失败
# data = data.reshape(2, 5, -1)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], 形状: (24,)

数组内容:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], 形状: (2, 12)

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)

数组内容:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], 形状: (24,)


## 3. 数组转置

转置是线性代数的一个概念, 及将 $m \times n$ 矩阵转置为 $n \times m$ 矩阵, 矩阵中元素的位置关系不变, 例如:

对于矩阵
$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$, 其转置矩阵为
$
A^T=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}
$

Numpy 支持多维数组 (多维矩阵), 故可对多维数组进行转置, 例如对于三维数组, 可将 $m \times n \times k$ 矩阵转置为 $k \times n \times m$

In [25]:
data = np.arange(1, 25).reshape(2, 3, 4)
print(f"数组内容:\n{data}, 形状: {data.shape}")

data = data.T
print(f"\n转置后数组内容:\n{data}, 形状: {data.shape}")

数组内容:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 形状: (2, 3, 4)

转置后数组内容:
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]], 形状: (4, 3, 2)
