# 矩阵

In [1]:
import numpy as np

from display import aprint

再 Numpy 中, 矩阵 (Matrix) 维度 (dim) 固定为 `2` 的数组 (二维数组)

- 矩阵乘法: `@`
- 矩阵转置: `.T`
- 矩阵转置: `.transpose()`
- 矩阵转置: `.conjugate_transpose()`
- 矩阵转置: `.conjugate()`
- 矩阵转置: `.conj()`
- 矩阵转置: `.H`
- 矩阵转置: `.T`
- 矩阵转置: `.transpose()`

可以将维度小于 `2` ($dim \le 2$) 的数组赋值给矩阵, 得到的矩阵对象维度 (dim) 会扩展为 `2`

In [20]:
# 通过 dim <= 2 的数组创建矩阵
# 无论是通过单值, 1 维数组以及 2 维数组创建矩阵, 都会将其维度扩展为 2 维
m1 = np.matrix(10)
m2 = np.matrix([10])
m3 = np.matrix([1, 2, 3, 4])
m4 = np.matrix([[1, 2, 3, 4]])
m5 = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
aprint(
    "矩阵",
    {
        "m1": m1,
        "m2": m2,
        "m3": m3,
        "m4": m4,
        "m5": m5,
    },
)

# 如果通过维度为 2 以上的数组创建矩阵, 则会导致错误
arr = [
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
]
try:
    m6 = np.matrix(arr)
except Exception as e:
    print(f"\n创建矩阵失败: {e}")

矩阵
- m1:
[[10]], shape=(1, 1)
- m2:
[[10]], shape=(1, 1)
- m3:
[[1 2 3 4]], shape=(1, 4)
- m4:
[[1 2 3 4]], shape=(1, 4)
- m5:
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4)

创建矩阵失败: matrix must be 2-dimensional


In [25]:
m1 = np.matrix([[1, 2], [3, 4]])
m2 = np.matrix([[10, 20, 30], [30, 40, 50]])
aprint(
    "矩阵相加",
    {
        "m1": m1,
        "m2": m2,
        "m1 + m2": m1 + m2,
    },
)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 