# 数组索引

In [2]:
import numpy as np

from display import aprint
from array_ import arange_by_shape

索引用于获取 Numpy 数组中的某个或某几个元素, 根据数组维度和索引维度的不同, 该元素可以是一个值或一个数组

## 1. 下标索引

### 1.1. 一维数组下标索引

通过下标索引可以获取数组指定位置的元素值

下标索引值的取值范围为 `0`~`数组长度 - 1` 或 `-1`~`-数组长度`, 前者从数组首位置开始计算, 而后者从数组末位置开始计算

In [ ]:
a = np.arange(10, dtype=np.int32)

aprint(
    "一维数组索引:",
    {
        "a": a,
        # 索引为正数, 表示从数组开头 (0) 开始计算
        "a[0]": a[0],
        "a[5]": a[5],
        # 索引为负数, 表示从数组末尾 (-1) 开始计算
        "a[-1]": a[-1],
        "a[-10]": a[-10],
    },
)

一维数组索引:
▶️ a:
[0 1 2 3 4 5 6 7 8 9], shape=(10,)
✅ a[0]:
0
✅ a[5]:
5
✅ a[-1]:
9
✅ a[-10]:
0


### 1.2. 多维数组下标索引

通过下标索引访问多维数组时, 返回的是某个维度下指定位置的数组元素值

可以通过多个连续的下标访问多维数组, 返回的是某个维度下指定位置的数组元素值, 例如下标 `[0][1][2]` 表示: 数组第一维的第 `0` 个元素结果第 `1` 个元素结果的第 `2` 个元素

In [ ]:
a = arange_by_shape((2, 3, 4), start=1)

aprint(
    "多维数组索引:",
    {
        "a": a,
        # 获取三维数组第一维的第一个元素, 结果为一个二维数组
        "a[0]": a[0],
        # 获取三维数组最后一维的元素, 结果为一个二维数组
        "a[-1]": a[-1],
        # 在第一个索引结果的基础上进一步通过第二个索引获取元素, 结果为一个一维数组
        "a[0][1]": a[0][1],
        # 在前两个索引结果的基础上进一步通过第三个索引获取元素, 结果为一个元素
        "a[0][1][2]": a[0][1][2],
    },
)

多维数组索引:
▶️ a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
✅ a[0]:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4)
✅ a[-1]:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]], shape=(3, 4)
✅ a[0][1]:
[5 6 7 8], shape=(4,)
✅ a[0][1][2]:
7


Numpy 支持多维数组索引的简写, 例如可将形如 `[0][1][2]` 的索引简写为 `[0, 1, 2]`

In [5]:
a = arange_by_shape((2, 3, 4), start=1)

aprint(
    "多维数组索引:",
    {
        "a": a,
        "a[0, 1]": a[0, 1],  # 获取数组第一维下的第一项以及第二维的
        "a[0, 1, 2]": a[0, 1, 2],
        "a[1, -1, -2]": a[1, -1, -2],
    },
)

多维数组索引:
▶️ a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
✅ a[0, 1]:
[5 6 7 8], shape=(4,)
✅ a[0, 1, 2]:
7
✅ a[1, -1, -2]:
23


## 2. 花式索引

Numpy 允许使用数组作为索引, 用于一次性批量获取对应数组多个索引对应的元素, 称为 "花式索引"

花式索引的结果为索引数组中每一项作为索引对应原数组的元素值

当 $A = \begin{bmatrix}
a_{0} & a_{1} & a_{2} & a_{3} & a_{4} & a_{5}
\end{bmatrix}$, 则 $A[[1, 3, 5]] = \begin{bmatrix}
a_{1} & a_{3} & a_{5}
\end{bmatrix}$, 其中 $a_{n}$ 可以为一个元素值, 或者一个子数组

**通过花式索引获取的数组元素仍会组成数组, 表示批量获取元素的结果**

### 2.1. 一维数组花式索引

#### 2.1.1. 一维花式索引

通过一维数组作为花式索引, 即可从原数组中获取对应索引的元素值, 例如: `a[[1, 3]]` 表示获取数组 `a` 索引为 `1` 和 `3` 的元素

In [6]:
a = np.arange(0, 15, step=1, dtype=np.int32)

aprint(
    "一维花式索引:",
    {
        "a": a,
        "a[[1, 3, 5]]": a[[1, 3, 5]],  # 获取数组中索引为 `1, 3, 5` 的元素
        "a[[-1, -3, -5]]": a[[-1, -3, -5]],  # 获取数组中索引为 `-1, -3, -5` 的元素
    },
)

一维花式索引:
▶️ a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,)
✅ a[[1, 3, 5]]:
[1 3 5], shape=(3,)
✅ a[[-1, -3, -5]]:
[14 12 10], shape=(3,)


#### 2.1.2. 多维花式索引

使用一维数组作为花式索引, 相当于一次性批量从原数组中获取若干元素, 组成结果数组

而使用二维数组作为花式索引, 则表示分多次从原数组中获取元素, 结果组成二维数组, 表示按索引的每一行多次从原数组中获取元素组成的结果

- 通过 `[[1], [3], [5]]` 作为花式索引, 返回一个由原数组索引为 `(1)`, `(3)`, `(5)` 的元素组成的三行一列的二维数组 (`shape = (3, 1)`)
- 通过 `[[1, 2], [3, 4], [5, 6]]` 作为花式索引, 返回一个由原数组索引为 `(1, 2)`, `(3, 4)`, `(5, 6)` 的元素组成的三行两列的二维数组 (`shape = (3, 2)`)

也可以理解为对原一维数组进行了广播, 将其变为二维数组, 然后再通过花式索引获取元素值, 例如对于形状为 `(10,)` 的数组, 使用形状为 `(3, 2)` 的花式索引, 相当于原数组广播为 `(3, 10)`, 然后再通过花式索引获取元素值, 结果为 `(3, 2)` 的二维数组

In [7]:
a = np.arange(0, 15, step=1, dtype=np.int32)

aprint(
    "二维花式索引",
    {
        "a": a,
        "a[[[1], [3], [5]]]": a[
            [
                [1],
                [3],
                [5],
            ]
        ],
        "a[[[1, 2], [3, 4], [5, 6]]]": a[
            [
                [1, 2],
                [3, 4],
                [5, 6],
            ],
        ],
    },
)

二维花式索引
▶️ a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,)
✅ a[[[1], [3], [5]]]:
[[1]
 [3]
 [5]], shape=(3, 1)
✅ a[[[1, 2], [3, 4], [5, 6]]]:
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2)


同理, 可以使用多维花式索引, 相当于对原一维数组进行广播后, 通过花式索引获取元素值

例如通过形状为 `(3, 2, 2)` 的花式索引获取原数组元素, 获取结果仍为 `(3, 2, 2)` 的数组

In [8]:
a = np.arange(0, 15, step=1, dtype=np.int32)

aprint(
    "多维花式索引:",
    {
        "a": a,
        "a[[[1, 2], [3, 4]], [[5, 6]]]": a[
            [
                [
                    [1, 2],
                    [3, 4],
                ],
                [
                    [5, 6],
                    [7, 8],
                ],
                [
                    [9, 10],
                    [11, 12],
                ],
            ]
        ],
    },
)

多维花式索引:
▶️ a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,)
✅ a[[[1, 2], [3, 4]], [[5, 6]]]:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2)


### 2.2. 多维数组花式索引

#### 2.2.1. 逐维度进行索引

对于多维数组, 可以使用多组花式索引, 后一组会在前一组获取元素的基础上进一步获取元素 (前一步获取的元素为一个数组)

可以通过多个数组索引来对应多维数组的各个维度, 例如对于一个三维数组, 则可通过如下索引方式获取各个维度元素:

- `a[[1, 3], [2, 4]]`: 获取第一维度索引为 `1` 和 `3` 的两项, 以及索引为 `1` 项中索引为 `2` 和索引为 `3` 项中索引为 `4` 的子项;
- `a[[1, 3], [2, 4], [3]]`: 获取第一维度索引为 `1` 和 `3` 的两项, 在此基础上获取索引为 `1` 项中索引为 `2` 和索引为 `3` 项中索引为 `4` 的子项, 以及索引为 `2` 和索引为 `4` 项中索引为 `3` 的子项;

In [9]:
a = arange_by_shape((3, 3, 3), 1)
aprint(
    "\n多维数组索引结果:",
    {
        "a": a,
        "a[[0, 2]]": a[[0, 2]],  # 获取数组索引为 `0`, `1` 的元素, 结果组成
        "a[[0, 2], [1, 2]]": a[
            [0, 2],
            [1, 2],
        ],  # 在第一组索引的基础上, 进一步通过第二组索引获取元素值
        "a[[0, 2], [1, 2], [0, 1]]": a[
            [0, 2],
            [1, 2],
            [0, 1],
        ],  # 通过三组索引获取元素值
    },
)


多维数组索引结果:
▶️ a:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3)
✅ a[[0, 2]]:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(2, 3, 3)
✅ a[[0, 2], [1, 2]]:
[[ 4  5  6]
 [25 26 27]], shape=(2, 3)
✅ a[[0, 2], [1, 2], [0, 1]]:
[ 4 26], shape=(2,)


#### 2.2.2. ddd 

In [10]:
a = arange_by_shape((4, 3, 3), 1)
aprint(
    "\n多维数组索引结果:",
    {
        "a": a,
        "a[[[0], [1], [2]]]": a[
            [
                [0],
                [1],
                [2],
            ]
        ],
        "a[[[0], [1], [2]], [[0, 1]]]": a[
            [
                [0],
                [1],
                [2],
            ],
            [
                [0, 1],
            ],
        ],
        "a[[[0], [1], [2]], [[0, 1]], [[0, 2]]]": a[
            [
                [0],
                [1],
                [2],
            ],
            [
                [0, 1],
            ],
            [
                [0, 2],
            ],
        ],
    },
)


多维数组索引结果:
▶️ a:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]], shape=(4, 3, 3)
✅ a[[[0], [1], [2]]]:
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]]


 [[[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]]], shape=(3, 1, 3, 3)
✅ a[[[0], [1], [2]], [[0, 1]]]:
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]], shape=(3, 2, 3)
✅ a[[[0], [1], [2]], [[0, 1]], [[0, 2]]]:
[[ 1  6]
 [10 15]
 [19 24]], shape=(3, 2)


### 2.3. 笛卡尔积索引

可以通过 `np.ix_` 函数来构建一个行和列交叉索引, 从而获取到集合的一个笛卡尔积

#### 2.3.1. 二维数组笛卡尔积索引

对于二维数组, 可以通过 `np.ix_` 函数创建索引, 获取数组中指定行和列的全部元素

本例中通过两个数组 `[0, 2, 4]` 和 `[1, 3, 5]`为参数, 则 `np.ix_` 函数返回结果为两个数组, 结果为:

$\begin{bmatrix}
    \begin{bmatrix}
        0
    \end{bmatrix} \\
    \begin{bmatrix}
        2
    \end{bmatrix} \\
    \begin{bmatrix}
        4
    \end{bmatrix}
\end{bmatrix} 以及 \begin{bmatrix}
    \begin{bmatrix}
        1 & 3 & 5
    \end{bmatrix}
\end{bmatrix}$

最终组成的索引为 `[[0, 1], [0, 3], [0, 5]], [[2, 1], [2, 3], [2, 5], [4, 1], [4, 3], [4, 5]]`

In [11]:
a = arange_by_shape((6, 6), 1)
idx = np.ix_([0, 2, 4], [1, 3, 5])  # 构建行和列交叉索引, 该索引的结果为 3x3 数组

aprint(
    "二维数组笛卡尔积索引为:",
    {
        "a": a,
        "idx": idx,
        "a[idx]": a[idx],
    },
)

二维数组笛卡尔积索引为:
▶️ a:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]], shape=(6, 6)
✅ idx:
(array([[0],
       [2],
       [4]]), array([[1, 3, 5]]))
✅ a[idx]:
[[ 2  4  6]
 [14 16 18]
 [26 28 30]], shape=(3, 3)


### 5.2 对于多维数组

In [12]:
a = arange_by_shape((3, 3, 3), 1)
idx = np.ix_([0, 1], [1, 2], [1, 0, 2])  # 构建行和列交叉索引, 该索引的结果为 2x2x3 数组

idx.

aprint(
    "多维数组笛卡尔积索引为:",
    {
        "a": a,
        "idx": idx,
        "a[idx]": a[idx],
    },
)

SyntaxError: invalid syntax (2463984050.py, line 4)

## 2. 布尔值索引

### 2.1. 以布尔值为数组索引

In [ ]:
a = np.arange(5, dtype=np.int32)

aprint(
    "布尔值索引:",
    {"a": a, "a[]": a[[True, False, True, False, True]]},
)

布尔值索引:
> a:
[0 1 2 3 4], shape=(5,)
> a[]:
[0 2 4], shape=(3,)


Numpy 索引可以为一个 "布尔" 值, 索引结果中会包含所有索引值为 `True` 的元素, 所以可以在索引中包含一个值为 "布尔" 值的表达式, 对数组进行过滤, 类似 `a[a > 0]`

过滤条件索引会对数组中的**所有维度**的元素进行计算, 如果该维度的元素可满足条件索引表达式的计算, 且满足条件索引表达式的计算结果为 `True`, 则该元素会被包含在结果数组中

In [ ]:
a = np.arange(10, dtype=np.int32)
aprint(
    "一维数组过滤结果:",
    {
        "a": a,
        "a[a > 5]": a[a > 5],  # 过滤所有值大于 `5 的元素
        "a[~(a > 5)]": a[~(a > 5)],  # 逻辑求反, 即过滤所有值小于等于 `5` 的元素
        "a[a % 2 == 0]": a[a % 2 == 0],  # 过滤所有值为偶数的元素
    },
)

a = arange_by_shape((4, 5), 1)
aprint(
    "\n多维数组过滤结果:",
    {
        "a": a,
        "a[a > 5]": a[
            a > 5
        ],  # 过滤所有值大于 `5` 的元素, 返回一个数组, 包含所有维度中值大于 `5` 的元素
        "a[~(a > 5)]": a[~(a > 5)],  # 逻辑求反, 即过滤所有维度中值小于等于 `5` 的元素
        "a[a % 2 == 0]": a[a % 2 == 0],  # 过滤所有维度中值为偶数的元素
        "a[np.sum(a, axis=1) > 50]": a[
            np.sum(a, axis=1)
            > 50  # 过滤数组元素求和值大于 `50` 的数组元素, 如果数组元素不满足 `np.sum` 计算要求, 则返回 `False`
        ],
    },
)

一维数组过滤结果:
> a:
[0 1 2 3 4 5 6 7 8 9], shape=(10,)
> a[a > 5]:
[6 7 8 9], shape=(4,)
> a[~(a > 5)]:
[0 1 2 3 4 5], shape=(6,)
> a[a % 2 == 0]:
[0 2 4 6 8], shape=(5,)

多维数组过滤结果:
> a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(4, 5)
> a[a > 5]:
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20], shape=(15,)
> a[~(a > 5)]:
[1 2 3 4 5], shape=(5,)
> a[a % 2 == 0]:
[ 2  4  6  8 10 12 14 16 18 20], shape=(10,)
> a[np.sum(a, axis=1) > 50]:
[[11 12 13 14 15]
 [16 17 18 19 20]], shape=(2, 5)
