# 数组切片

In [118]:
import numpy as np

from display import aprint
from array_ import arange_by_shape

数组的切片用于从数组中切割出一个新数组, 可以通过 Python 元素的 `slice` 对象进行切片, 也可以通过 Numpy 特有的 `:` 语法进行切片 (由于 Numpy 对数组索引做了特殊定义, 所以通过 `:` 语法取代 Python 元素的切片语法)

## 1. 切片语法

和 Python 数组类似, Numpy 数组也可以通过 `slice` 对象以及 `[start:stop:step]` 符号进行切片

### 1.1. `slice` 对象

通过 `slice` 函数可以创建切片对象, 格式为 `slice(start, stop, step)`, 其中:

- `start` 表示切片的起始位置
- `stop` 表示切片的结束位置
- `step` 表示切片的步长

通过 `slice` 对象, 可以对数组进行切片操作

In [119]:
# 定义一个一维数组
a = np.arange(1, 5, step=1)

# 定义一个切片对象
s = slice(1, 3, 1)

# 通过切片对象获取数组内容进行截取
print(f"数组 a = {a}, s = {slice(1, 2, 1)}, 则:")
print(f"a[s] = {a[s]}")

数组 a = [1 2 3 4], s = slice(1, 2, 1), 则:
a[s] = [2 3]


### 1.2. `[start:stop:step]` 符号

通过 `[start:stop:step]` 运算符, 可以直接对数组进行切片操作, 返回切片结果

- `start` 表示切片的起始位置
- `stop` 表示切片的结束位置
- `step` 表示切片的步长

In [120]:
a = np.arange(1, 5, step=1)

print(f"数组 a = {a}, 则:")
print(f"a[1:3:1] = {a[1:3:1]}")

数组 a = [1 2 3 4], 则:
a[1:3:1] = [2 3]


### 1.3. 切片值缺省值

对于 `[start:stop:step]` 切片, 其中 `start`, `stop` 和 `step` 三个值都可以缺省, 其中:

- `start` 的缺省值为 `0`, 表示切片起始于数组第一个元素
- `stop` 的缺省值为 `数组长度+1`, 表示切片结束于数组最后一个元素
- `step` 表示切片的步长, 默认为 `1`, 表示切片间隔为 `1` 个数组元素

对于 `start` 和 `stop` 值来说, 缺省时不能省略其间隔的 `:`, 而如果 `step` 缺省时, 可以同时省略其前面的的 `:`, 例如对于一个长度为 `len` 的数组:

- `a[start:stop]` 等价于 `a[start:stop:1]`
- `a[start:]` 等价于 `a[start:len+1:1]`
- `a[:stop]` 等价于 `a[1:stop:1]`
- `a[::step]` 等价于 `a[1:len+1:step]`
- `a[:]` 等价于 `a[1:len+1:1]`

In [136]:
a = np.arange(1, 8, step=1)

print(f"数组 a = {a}, 则:")
print(f"a[2:5] = {a[2:5]}\t a[2:5:1] = {a[2:5:1]}")
print(f"a[2:] = {a[2:]}\t a[2:len(a)+1:1] = {a[2:len(a)+1:1]}")
print(f"a[:5] = {a[:5]}\t a[0:5:1] = {a[0:5:1]}")
print(f"a[::2] = {a[::2]}\t a[0:len(a)+1:2] = {a[0:len(a)+1:2]}")
print(f"a[:] = {a[:]}\t a[0:len(a)+1:1] = {a[0:len(a)+1:1]}")

数组 a = [1 2 3 4 5 6 7], 则:
a[2:5] = [3 4 5]	 a[2:5:1] = [3 4 5]
a[2:] = [3 4 5 6 7]	 a[2:len(a)+1:1] = [3 4 5 6 7]
a[:5] = [1 2 3 4 5]	 a[0:5:1] = [1 2 3 4 5]
a[::2] = [1 3 5 7]	 a[0:len(a)+1:2] = [1 3 5 7]
a[:] = [1 2 3 4 5 6 7]	 a[0:len(a)+1:1] = [1 2 3 4 5 6 7]


### 1.4. 在切片中使用负数

对于切片 `[start:stop:step]` 语法来说, `start`, `stop` 和 `stop` 三个值均可以为负数, 负数的含义为:

- 对于 `start` 和 `stop` 值来说, 负数表示从数组末尾开始计算位置, 其中 `-1` 表示数组最后一个元素, 

In [122]:
a = np.arange(1, 5, step=1)

a[-1::-1]

array([4, 3, 2, 1])

## 1. 一维数组切片

### 1.1. `slice` 函数切片

一维数组可以通过 Python 本身的 Slice (切片) 对象进行切片

### 1.2. `:` 符号切片

一维数组也可以通过 Numpy 的切片语法 (`:`) 来进行切片, 语法为 `[起始索引:结束索引:步长]`, 将截取 $\small \left(起始索引, 结束索引\right]$ 之间的元素

如果省略切片的 "起始索引", 即 (:结束索引:步长), 则默认为 "起始索引为 `0`"; 如果省略切片的 "结束索引", 即 (开始索引::步长), 则默认为 "结束索引为 `-1`", 即最后一个索引; 如果省略切片的 "步长", 即 (开始索引:结束索引), 则默认为 "步长为 `1`"

如果切片步长为负数 (例如 `-1`), 则结果数组为元素住的逆序, 例如 `[::-1]` 表示切片结果为从数组的最后一个元素开始到第一个元素的逆序, `[-2::-2]` 表示切片结果为从数组倒数第二个元素开始到第一个元素的逆序, 间隔两个元素, 而 `[-2:0:-1]` 表示切片结果为从数组倒数第二个元素开始到第二个元素的逆序, 间隔一个元素

In [123]:
a = np.arange(1, 10, step=1)

aprint(
    "一维数组切片:",
    {
        "a": a,
        "a[1]": a[1],
        "a[1:3]": a[1:6],
        "a[1:3:2]": a[1:6:2],
        "a[1:]": a[1:],
        "a[:6]": a[:6],
        "a[::2]": a[::2],
        "a[2:-1]": a[2:-1],
        "a[::-1]": a[::-1],
        "a[-2::-1]": a[-2::-1],
        "a[-2:0:-1]": a[-2:0:-1],
    },
)

一维数组切片:
> a:
[1 2 3 4 5 6 7 8 9], shape=(9,)
> a[1]:
2
> a[1:3]:
[2 3 4 5 6], shape=(5,)
> a[1:3:2]:
[2 4 6], shape=(3,)
> a[1:]:
[2 3 4 5 6 7 8 9], shape=(8,)
> a[:6]:
[1 2 3 4 5 6], shape=(6,)
> a[::2]:
[1 3 5 7 9], shape=(5,)
> a[2:-1]:
[3 4 5 6 7 8], shape=(6,)
> a[::-1]:
[9 8 7 6 5 4 3 2 1], shape=(9,)
> a[-2::-1]:
[8 7 6 5 4 3 2 1], shape=(8,)
> a[-2:0:-1]:
[8 7 6 5 4 3 2], shape=(7,)


## 2. 多维数组切片

对于多维数组, 主要是通过 Numpy 提供的 `:` 切片语法进行, 可以用 `,` 分隔来表示对特定维度的部分进行切片, 例如对于 shape=`(2, 3, 4)` 的数组, 可以有如下切片:
- 通过 `[1:2:1]` 表示对第一个维进行切片, 即将三维数组看作是一个长度为 `2` 的一维数组, 取其中第二个元素;
- 通过 `[:, 1:2:1]` 来表示对第二个维进行切片, 即将三维数组看作是一个两行两列的二维数组, 第一维全部保留, 第二维取第二个元素;
- 通过 `[:, :, 1:2:1]` 来表示对第三个维进行切片, 即将三维数组看作是一个两行两列两层的三维数组, 第一维和第二维全部保留, 第三维取第二个元素;

In [124]:
a = arange_by_shape((2, 3, 4), 1)

aprint(
    "多维数组切片:",
    {
        "a": a,
        "a[1:2:1]": a[1:2:1],  # 对第一维度进行切片
        "a[:, 1:2:1]": a[:, 1:2:3],  # 对第二维度进行切片
        "a[:, :, 1:2:1]": a[:, :, 1:2:1],  # 对第三维度进行切片
        "a[1:2:1, 1:2:1]": a[1:2:1, 1:2:1],  # 对第一, 二维度进行切片
        "a[1:2:1, :, 1:2:1]": a[1:2:1, :, 1:2:1],  # 对第一, 三维度进行切片
        "a[1:2:1, 1:2:1, 1:2:1]": a[1:2:1, 1:2:1, 1:2:1],  # 对第一, 二, 三维度进行切片
    },
)

多维数组切片:
> a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
> a[1:2:1]:
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(1, 3, 4)
> a[:, 1:2:1]:
[[[ 5  6  7  8]]

 [[17 18 19 20]]], shape=(2, 1, 4)
> a[:, :, 1:2:1]:
[[[ 2]
  [ 6]
  [10]]

 [[14]
  [18]
  [22]]], shape=(2, 3, 1)
> a[1:2:1, 1:2:1]:
[[[17 18 19 20]]], shape=(1, 1, 4)
> a[1:2:1, :, 1:2:1]:
[[[14]
  [18]
  [22]]], shape=(1, 3, 1)
> a[1:2:1, 1:2:1, 1:2:1]:
[[[18]]], shape=(1, 1, 1)


## 3. 切片占位符

通过 `...` 符号可以在 Numpy 切片中作为占位符, 其作用表示 "选择所有剩余维度", 而无需使用多个 `:` 符号, 例如:

- `a[:, :, 1]` 和 `a[..., 1]` 等价
- `a[1, :, :]` 和 `a[1, ...]` 等价
- `a[1, :, :, 1]` 和 `a[1, ..., 1]` 等价

In [125]:
a = arange_by_shape((2, 3, 4), 1)

aprint(
    "多维数组切片:",
    {
        "a": a,
        "a[1, ...]": a[1, ...],  # 相当于 `a[1, :, :]`
        "a[0:1:1, ...]": a[0:1:1, ...],  # 相当于 `a[0:1:1, :, :]`
        "a[..., 2]": a[..., 2],  # 相当于 `a[:, :, 2]`
        "a[..., 2:3]": a[..., 2:3],  # 相当于 `a[:, :, 2:3]`
        "a[1, ..., 2]": a[1, ..., 2],  # 相当于 `a[1, :, 2]`
    },
)

多维数组切片:
> a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4)
> a[1, ...]:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]], shape=(3, 4)
> a[0:1:1, ...]:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(1, 3, 4)
> a[..., 2]:
[[ 3  7 11]
 [15 19 23]], shape=(2, 3)
> a[..., 2:3]:
[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]], shape=(2, 3, 1)
> a[1, ..., 2]:
[15 19 23], shape=(3,)
