# 数组索引

In [1]:
import numpy as np

from display import aprint
from array_ import arange_by_shape

索引用于获取 Numpy 数组中的某个元素, 根据数组维度和索引维度的不同, 该元素可以是一个值或一个数组

## 1. 一维数组索引

Numpy 一维数组的索引类似于 Python 数组的索引, 获取索引指定位置的数组元素值

In [2]:
a = np.arange(10, dtype=np.int32)

aprint(
    "一维数组索引:",
    {
        "a": a,
        "a[0]": a[0],  # 返回数组元素
        "a[5]": a[5],
        "a[-1]": a[-1],  # 返回数组最后一个元素
    },
)

一维数组索引:
> a:
[0 1 2 3 4 5 6 7 8 9], shape=(10,)
> a[0]:
0
> a[5]:
5
> a[-1]:
9


## 2. 二维数组索引

二维数组相当于多个一维数组的集合, 所以通过一维索引结果为一维数组, 通过二维索引结果为元素, 即:

- 一维索引: `a[i]`
- 二维索引: `a[i, j]`

In [3]:
a = arange_by_shape((3, 5), 1)

aprint(
    "一维数组索引:",
    {
        "a": a,
        "a[0]": a[0],  # 返回第二维的数组
        "a[-1]": a[-1],  # 返回第二维最后一个数组
        "a[1, 2]": a[1, 2],  # 返回元素值
        "a[0, -1]": a[0, -1],
    },
)

一维数组索引:
> a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]], shape=(3, 5)
> a[0]:
[1 2 3 4 5], shape=(5,)
> a[-1]:
[11 12 13 14 15], shape=(5,)
> a[1, 2]:
8
> a[0, -1]:
5


## 3. 多维数组索引

多维数组相当于二维数组的一个延申, 通过指定维度的索引可以访问数组中对应维度的元素

In [4]:
a = arange_by_shape((3, 4, 5), 1)

aprint(
    "多维数组索引:",
    {
        "a": a,
        "a[0]": a[0],  # 返回第二维的数组
        "a[-1]": a[-1],
        "a[1, 2]": a[1, 2],  # 返回第三维的数组
        "a[0, -1]": a[0, -1],
        "a[1, 2, 3]": a[1, 2, 3],  # 返回元素值
        "a[1, -1, 3]": a[1, -1, 3],
    },
)

多维数组索引:
> a:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]], shape=(3, 4, 5)
> a[0]:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(4, 5)
> a[-1]:
[[41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]], shape=(4, 5)
> a[1, 2]:
[31 32 33 34 35], shape=(5,)
> a[0, -1]:
[16 17 18 19 20], shape=(5,)
> a[1, 2, 3]:
34
> a[1, -1, 3]:
39


## 4. 过滤条件索引

Numpy 索引可以为一个 "布尔" 值, 索引结果中会包含所有索引值为 `True` 的元素, 所以可以在索引中包含一个值为 "布尔" 值的表达式, 对数组进行过滤, 类似 `a[a > 0]`

过滤条件索引会对数组中的**所有维度**的元素进行计算, 如果该维度的元素可满足条件索引表达式的计算, 且满足条件索引表达式的计算结果为 `True`, 则该元素会被包含在结果数组中

In [5]:
a = np.arange(10, dtype=np.int32)
aprint(
    "一维数组过滤结果:",
    {
        "a": a,
        "a[a > 5]": a[a > 5],  # 过滤所有值大于 `5 的元素
        "a[~(a > 5)]": a[~(a > 5)],  # 逻辑求反, 即过滤所有值小于等于 `5` 的元素
        "a[a % 2 == 0]": a[a % 2 == 0],  # 过滤所有值为偶数的元素
    },
)

a = arange_by_shape((4, 5), 1)
aprint(
    "\n多维数组过滤结果:",
    {
        "a": a,
        "a[a > 5]": a[
            a > 5
        ],  # 过滤所有值大于 `5` 的元素, 返回一个数组, 包含所有维度中值大于 `5` 的元素
        "a[~(a > 5)]": a[~(a > 5)],  # 逻辑求反, 即过滤所有维度中值小于等于 `5` 的元素
        "a[a % 2 == 0]": a[a % 2 == 0],  # 过滤所有维度中值为偶数的元素
        "a[np.sum(a, axis=1) > 50]": a[
            np.sum(a, axis=1)
            > 50  # 过滤数组元素求和值大于 `50` 的数组元素, 如果数组元素不满足 `np.sum` 计算要求, 则返回 `False`
        ],
    },
)

一维数组过滤结果:
> a:
[0 1 2 3 4 5 6 7 8 9], shape=(10,)
> a[a > 5]:
[6 7 8 9], shape=(4,)
> a[~(a > 5)]:
[0 1 2 3 4 5], shape=(6,)
> a[a % 2 == 0]:
[0 2 4 6 8], shape=(5,)

多维数组过滤结果:
> a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(4, 5)
> a[a > 5]:
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20], shape=(15,)
> a[~(a > 5)]:
[1 2 3 4 5], shape=(5,)
> a[a % 2 == 0]:
[ 2  4  6  8 10 12 14 16 18 20], shape=(10,)
> a[np.sum(a, axis=1) > 50]:
[[11 12 13 14 15]
 [16 17 18 19 20]], shape=(2, 5)


## 5. 数组索引 (花式索引)

Numpy 允许使用数组作为索引, 用于一次性批量获取对应数组多个索引对应的元素

例如: `a[[1, 3]]` 表示获取数组 `a` 索引为 `1` 和 `3` 的元素, 其中:

- 如果数组 `a` 是一维数组, 则返回 `1` 和 `3` 对应的元素值, 结果为一个一维数组
- 如果数组 `a` 是多维数组, 则返回 `1` 和 `3` 行的全部元素值, 结果为一个多维数组

当 $A = \begin{bmatrix}
a_{0} & a_{1} & a_{2} & a_{3} & a_{4} & a_{5}
\end{bmatrix}$, 则 $A[[1, 3, 5]] = \begin{bmatrix}
a_{1} & a_{3} & a_{5}
\end{bmatrix}$, 其中 $a_{n}$ 可以为一个元素值, 或者一个多维数组

可以通过多个数组索引来对应多维数组的各个维度, 例如对于一个三维数组, 则可通过如下索引方式获取各个维度元素:

- `a[[1, 3]]`: 获取第一维度索引为 `1` 和 `3` 的两个二维数组;
- `a[[1, 3], [2, 4]]`: 获取第一维度索引为 `1` 和 `3` 的两项, 以及索引为 `1` 项中索引为 `2` 和索引为 `3` 项中索引为 `4` 的子项;
- `a[[1, 3], [2, 4], [3]]`: 获取第一维度索引为 `1` 和 `3` 的两项, 在此基础上获取索引为 `1` 项中索引为 `2` 和索引为 `3` 项中索引为 `4` 的子项, 以及索引为 `2` 和索引为 `4` 项中索引为 `3` 的子项;

In [6]:
a = np.arange(0, 100, step=10, dtype=np.int32)
aprint(
    "一维数组索引结果:",
    {
        "a": a,
        "a[[1, 3, 5]]": a[[1, 3, 5]],  # 获取数组中索引为 `1, 3, 5` 的元素
        "a[[-1, -3, -5]]": a[
            [-1, -3, -5]
        ],  # 获取数组中索引为 `-1, -3, -5` 的元素 (反向索引)
    },
)

a = arange_by_shape((3, 3, 3), 1)
aprint(
    "\n多维数组索引结果:",
    {
        "a": a,
        "a[[0, 1]]": a[
            [0, 1]
        ],  # 获取数组中索引为 `0`, `1` 的元素, 即数组第一维的前两项
        "a[[0, 1], [1, 2]]": a[
            [0, 1],
            [1, 2],
        ],  # 在数组第一维的前两项基础上, 获取第 `1` 项中索引为 `1` 的项以及 第 `2` 项中索引为 `2` 的项
        "a[[0, 1], [1, 2], [0, 1]]": a[
            [0, 1],
            [1, 2],
            [0, 1],
        ],  # 在上述索引的基础上, 获取第 `1` 项中索引为 `0` 的项以及 第 `2` 项中索引为 `1` 的项
    },
)

一维数组索引结果:
> a:
[ 0 10 20 30 40 50 60 70 80 90], shape=(10,)
> a[[1, 3, 5]]:
[10 30 50], shape=(3,)
> a[[-1, -3, -5]]:
[90 70 50], shape=(3,)

多维数组索引结果:
> a:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3)
> a[[0, 1]]:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3)
> a[[0, 1], [1, 2]]:
[[ 4  5  6]
 [16 17 18]], shape=(2, 3)
> a[[0, 1], [1, 2], [0, 1]]:
[ 4 17], shape=(2,)


可以通过 `np.ix_` 函数来构建一个行和列交叉索引, 从而获取到集合的一个笛卡尔积

例如对于一个 shape=`(5, 5)` 的二位数组, 通过 `np.ix_([0, 2, 4], [1, 3, 4])` 可以获取到 `(0, 1)`, `(0, 3)`, `(0, 4)`, `(2, 1)`, `(2, 3)`, `(2, 4)`, `(4, 1)`, `(4, 3)`, `(4, 4)` 这一系列索引, 根据索引的形状 ($3 \times 3$), 可以得到如下结果：

$设: A = \begin{bmatrix}
    \begin{bmatrix}
        1 & 2 & 3 & 4 & 5
    \end{bmatrix} \\
    \begin{bmatrix}
        6 & 7 & 8 & 9 & 10
    \end{bmatrix} \\
    \begin{bmatrix}
        11 & 12 & 13 & 14 & 15
    \end{bmatrix} \\
    \begin{bmatrix}
        16 & 17 & 18 & 19 & 20
    \end{bmatrix} \\
    \begin{bmatrix}
        21 & 22 & 23 & 24 & 25
    \end{bmatrix}
\end{bmatrix}, 则：A[np.ix\_([0, 2, 4], [1, 3, 4])] = \begin{bmatrix}
    \begin{bmatrix}
        A[[0, 1]] & A[[0, 3]] & A[[0, 4]]
    \end{bmatrix} \\
    \begin{bmatrix}
        A[[2, 1]] & A[[2, 3]] & A[[2, 4]]
    \end{bmatrix} \\
    \begin{bmatrix}
        A[[4, 1]] & A[[4, 3]] & A[[4, 4]]
    \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
    \begin{bmatrix}
        2 & 4 & 5
    \end{bmatrix} \\
    \begin{bmatrix}
        12 & 14 & 15
    \end{bmatrix} \\
    \begin{bmatrix}
        22 & 24 & 25
    \end{bmatrix}
\end{bmatrix}$

### 5.1 对于二维数组

In [7]:
a = arange_by_shape((5, 5), 1)
idx = np.ix_([0, 2, 4], [1, 3, 4])  # 构建行和列交叉索引, 该索引的结果为 3x3 数组

aprint(
    "二维数组笛卡尔积索引为:",
    {
        "a": a,
        "idx": idx,
        "a[idx]": a[idx],
    },
)

二维数组笛卡尔积索引为:
> a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5)
> idx:
(array([[0],
       [2],
       [4]]), array([[1, 3, 4]]))
> a[idx]:
[[ 2  4  5]
 [12 14 15]
 [22 24 25]], shape=(3, 3)


### 5.2 对于多维数组

In [8]:
a = arange_by_shape((3, 3, 3), 1)
idx = np.ix_([0, 1], [1, 2], [1, 0, 2])  # 构建行和列交叉索引, 该索引的结果为 2x2x3 数组

aprint(
    "多维数组笛卡尔积索引为:",
    {
        "a": a,
        "idx": idx,
        "a[idx]": a[idx],
    },
)

多维数组笛卡尔积索引为:
> a:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3)
> idx:
(array([[[0]],

       [[1]]]), array([[[1],
        [2]]]), array([[[1, 0, 2]]]))
> a[idx]:
[[[ 5  4  6]
  [ 8  7  9]]

 [[14 13 15]
  [17 16 18]]], shape=(2, 2, 3)
